### ISSUE TITLE
sqt2pin excluding decoy psms from xml-files

### ISSUE THREAD

**Issue by percolator** [percolator/percolator#101]
Mike Riffle: ..., the pin.xml file does not contain any decoy PSMs. See the following:

```
mriffle@apollo:/data/keck/ms2/1395$ grep 'isDecoy' pin.xml | grep -c false
7410
mriffle@apollo:/data/keck/ms2/1395$ grep 'isDecoy' pin.xml | grep -c true
0
```

Note that 7411 is the number of PSMs in the target SQT file. I am not sure where the 1 missing PSM went, either.

Also note that it is missing all the decoys if I output as tab delimited data instead of XML.

**Comment by MatthewThe** [comment]
Not reproducible. What could have happened is that the decoy protein pattern (`-P` flag for the converters) was not correctly given to the converter.
