### ISSUE TITLE
msgf2pin

### ISSUE THREAD

**Issue by adder** [percolator/percolator#117]
Hi
The answer is probably obvious but I don't seem to find the `msgf2pin` command. I suppose it comes with the base percolator insstallation. I have succesfully used `percolator` and `qvality` commands on the comandline so I guess the installation was succesful, but i find nowhere documentation on how to use the msgf2pin converter functionality. There is no `msgf2pin` command in my path and I don't find it under `percolator -h`. Can you explain me how to use this functionality?

Thanks
greets

**Comment by MatthewThe** [comment]
You have to install the percolator-converters package. Good luck!
