### ISSUE TITLE
Modification information in Percolator's result.

### ISSUE THREAD

**Issue by fcyu** [percolator/percolator#126]
Since Percolator uses SVM to train a model, is it possible to let Percolator use Xcorr only? Or even more, letting Percolator use user-defined features?

thx

**Comment by percolator** [comment]
Yes, percolator can take a tab-delimited file with your own favorite
features as input. The format is described here;
https://github.com/percolator/percolator/wiki/Interface

Thanks
-Lukas

On Wed, May 20, 2015 at 3:29 AM, fcyu <notifications@github.com> wrote:

> Since Percolator uses SVM to train a model, is it possible to let
> Percolator use Xcorr only? Or even more, letting Percolator use
> user-defined features?
>
> thx
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/percolator/percolator/issues/126>.
>



-- 
========================
Lukas Käll
http://kaell.org
Royal Institute of Technology - KTH
Science for Life Laboratory
School of Biotechnology
Box 1031, 171 65 Solna, Sweden
+46 8 52481196 or
+46 76 9425179

**Comment by fcyu** [comment]
Thanks for the reply. One more stupid question. How can I know if an identified peptide has a modification from the output tsv file? Because I didn't find the fix modification marker in my result.

thx

**Comment by MatthewThe** [comment]
Normally modifications show up as `[UNIMOD:##]`. However, Percolator itself does not change peptide strings, so make sure the modifications are present in the input file. Did you use one of the converters (e.g. `sqt2pin`)?

**Comment by fcyu** [comment]
I direct use comet's tsv output as Percolator's input. Comet adds a star behind the amino acid with a variable modification, and nothing behind the amino acid with a fix modification. I think its comet's issue.

**Comment by thabangh** [comment]
The new version of Comet adds an additional column to provide detailed info
about mods.

**Comment by thabangh** [comment]
The new version of Comet adds an additional column to provide detailed info
about mods.

**Comment by fcyu** [comment]
I am using comet-2015012 which is the latest version. Unfortunately, there is no such column.

**Comment by thabangh** [comment]
It is described here:

http://comet-ms.sourceforge.net/release/release_201501/


   - Add modification column to text output. The encoding includes
   position, static or variable modification, and mass change for each
   modification in the peptide. Requested by Noble lab.

**Comment by fcyu** [comment]
I knew that. But I checked the output and source code again. percolator output file don't have this column. Please read the following code:

CometWritePercolator.cpp:
```
void CometWritePercolator::WritePercolatorHeader(FILE *fpout)
{
   // Write header line
   fprintf(fpout, "id\t");
   fprintf(fpout, "label\t");
   fprintf(fpout, "ScanNr\t");
   fprintf(fpout, "lnrSp\t");
   fprintf(fpout, "deltLCn\t");
   fprintf(fpout, "deltCn\t");
   fprintf(fpout, "lnExpect\t");
   fprintf(fpout, "Xcorr\t");
   fprintf(fpout, "Sp\t");
   fprintf(fpout, "IonFrac\t");
   fprintf(fpout, "Mass\t");
   fprintf(fpout, "PepLen\t");
   for (int i=1 ; i<= g_staticParams.options.iMaxPrecursorCharge; i++)
      fprintf(fpout, "Charge%d\t", i);
   fprintf(fpout, "enzN\t");
   fprintf(fpout, "enzC\t");
   fprintf(fpout, "enzInt\t");
   fprintf(fpout, "lnNumSP\t");
   fprintf(fpout, "dM\t");
   fprintf(fpout, "absdM\t");
   fprintf(fpout, "peptide\t");
   fprintf(fpout, "proteinId1\n");

   fflush(fpout);
}
```

```
void CometWritePercolator::PrintPercolatorSearchHit(int iWhichQuery,
                                                    int iWhichResult,
                                                    bool bDecoy,
                                                    Results *pOutput,
                                                    FILE *fpout,
                                                    double dDeltaCn,
                                                    double dLastDeltaCn)
{
  // Something else
  // ...

   // construct modified peptide string
   char szModPep[512];
   szModPep[0]='\0';

   // Write the peptide sequence in the same format as an sqt file.
   sprintf(szModPep+strlen(szModPep), "%c.", pOutput[iWhichResult].szPrevNextAA[0]);

   if (g_staticParams.variableModParameters.bVarModSearch
         && pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide] > 0)
   {
      sprintf(szModPep+strlen(szModPep), "n%c",
            g_staticParams.variableModParameters.cModCode[pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide]-1]);
   }

   for (int i = 0; i<pOutput[iWhichResult].iLenPeptide; i++)
   {
      sprintf(szModPep+strlen(szModPep), "%c", pOutput[iWhichResult].szPeptide[i]);

      if (g_staticParams.variableModParameters.bVarModSearch
            && !isEqual(g_staticParams.variableModParameters.varModList[pOutput[iWhichResult].pcVarModSites[i]-1].dVarModMass, 0.0))
      {
         sprintf(szModPep+strlen(szModPep), "%c",
               g_staticParams.variableModParameters.cModCode[pOutput[iWhichResult].pcVarModSites[i]-1]);
      }
   }

   if (g_staticParams.variableModParameters.bVarModSearch
         && pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide+1] > 1)
   {
      sprintf(szModPep+strlen(szModPep), "c%c",
            g_staticParams.variableModParameters.cModCode[pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide+1]-1]);
   }

   sprintf(szModPep+strlen(szModPep), ".%c", pOutput[iWhichResult].szPrevNextAA[1]);

   fprintf(fpout, "%s\t", szModPep);

   fprintf(fpout, "%s\n", pOutput[iWhichResult].szProtein);
}
```

The first part prints the header of Percolator file. The second part prints the "modified" peptide string that will be only a '*' behind the modified amino acid.

thx

**Comment by thabangh** [comment]
Yes, this is correct.  The modification column is only in the tab-delimited
output format, which is different from the tab-delimited PIN format. We
could ask Jimmy Eng to add this, but I don't know if it would mess
Percolator up.
Bill

**Comment by fcyu** [comment]
I think the best way is adding a mass with brackets to the end of modified amino acid. It won't change the column of percolator input file.
________________________________

**Comment by thabangh** [comment]
The issue is that a simple mass doesn't tell the whole story.  It doesn't
discriminate between static and variable modifications, nor between normal,
n-terminal peptide and n-terminal protein mods.  But perhaps Lukas can
weigh in on how he'd like modifications to be represented in the Percolator
input format.  Is that format documented somewhere?

Bill

**Comment by percolator** [comment]
Right now percolator interprets any string enclosed by squared brackets as
a PTM of the preceding aminoacid. That is you can represent a phospho
tyrosine as T[p], T[+80] or T[UNIMOD:21]. The Unimod notation is preferred
as it is an unambiguous notation.

-Lukas



On Thu, May 21, 2015 at 4:28 PM, thabangh <notifications@github.com> wrote:

> The issue is that a simple mass doesn't tell the whole story. It doesn't
> discriminate between static and variable modifications, nor between normal,
> n-terminal peptide and n-terminal protein mods. But perhaps Lukas can
> weigh in on how he'd like modifications to be represented in the Percolator
> input format. Is that format documented somewhere?
>
> Bill
>
>
>
> On Thu, May 21, 2015 at 7:14 AM, Fengchao <notifications@github.com>
> wrote:
>
> > I think the best way is adding a mass with brackets to the end of
> modified
> > amino acid. It won't change the column of percolator input file.
> > ________________________________
> > From: thabangh <notifications@github.com>
> > Sent: Thursday, May 21, 2015 9:56:03 PM
> > To: percolator/percolator
> > Cc: Fengchao YU
> > Subject: Re: [percolator] Modification information in Percolator's
> result.
> > (#126)
> >
> >
> > Yes, this is correct. The modification column is only in the
> tab-delimited
> > output format, which is different from the tab-delimited PIN format. We
> > could ask Jimmy Eng to add this, but I don't know if it would mess
> > Percolator up.
> > Bill
> >
> >
> > On Wed, May 20, 2015 at 10:00 PM, Fengchao <notifications@github.com>
> > wrote:
> >
> > > I knew that. But I checked the output and source code again. percolator
> > > output file don't have this column. Please read the following code:
> > >
> > > CometWritePercolator.cpp:
> > >
> > > void CometWritePercolator::WritePercolatorHeader(FILE *fpout)
> > > {
> > > // Write header line
> > > fprintf(fpout, "id\t");
> > > fprintf(fpout, "label\t");
> > > fprintf(fpout, "ScanNr\t");
> > > fprintf(fpout, "lnrSp\t");
> > > fprintf(fpout, "deltLCn\t");
> > > fprintf(fpout, "deltCn\t");
> > > fprintf(fpout, "lnExpect\t");
> > > fprintf(fpout, "Xcorr\t");
> > > fprintf(fpout, "Sp\t");
> > > fprintf(fpout, "IonFrac\t");
> > > fprintf(fpout, "Mass\t");
> > > fprintf(fpout, "PepLen\t");
> > > for (int i=1 ; i<= g_staticParams.options.iMaxPrecursorCharge; i++)
> > > fprintf(fpout, "Charge%d\t", i);
> > > fprintf(fpout, "enzN\t");
> > > fprintf(fpout, "enzC\t");
> > > fprintf(fpout, "enzInt\t");
> > > fprintf(fpout, "lnNumSP\t");
> > > fprintf(fpout, "dM\t");
> > > fprintf(fpout, "absdM\t");
> > > fprintf(fpout, "peptide\t");
> > > fprintf(fpout, "proteinId1\n");
> > >
> > > fflush(fpout);
> > > }
> > >
> > > void CometWritePercolator::PrintPercolatorSearchHit(int iWhichQuery,
> > > int iWhichResult,
> > > bool bDecoy,
> > > Results *pOutput,
> > > FILE *fpout,
> > > double dDeltaCn,
> > > double dLastDeltaCn)
> > > {
> > > // Something else
> > > // ...
> > >
> > > // construct modified peptide string
> > > char szModPep[512];
> > > szModPep[0]='\0';
> > >
> > > // Write the peptide sequence in the same format as an sqt file.
> > > sprintf(szModPep+strlen(szModPep), "%c.",
> > pOutput[iWhichResult].szPrevNextAA[0]);
> > >
> > > if (g_staticParams.variableModParameters.bVarModSearch
> > > &&
> > pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide] >
> 0)
> > > {
> > > sprintf(szModPep+strlen(szModPep), "n%c",
> > >
> >
> g_staticParams.variableModParameters.cModCode[pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide]-1]);
> > > }
> > >
> > > for (int i = 0; i<pOutput[iWhichResult].iLenPeptide; i++)
> > > {
> > > sprintf(szModPep+strlen(szModPep), "%c",
> > pOutput[iWhichResult].szPeptide[i]);
> > >
> > > if (g_staticParams.variableModParameters.bVarModSearch
> > > &&
> >
> !isEqual(g_staticParams.variableModParameters.varModList[pOutput[iWhichResult].pcVarModSites[i]-1].dVarModMass,
> > 0.0))
> > > {
> > > sprintf(szModPep+strlen(szModPep), "%c",
> > >
> >
> g_staticParams.variableModParameters.cModCode[pOutput[iWhichResult].pcVarModSites[i]-1]);
> > > }
> > > }
> > >
> > > if (g_staticParams.variableModParameters.bVarModSearch
> > > &&
> > pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide+1]
> >
> > 1)
> > > {
> > > sprintf(szModPep+strlen(szModPep), "c%c",
> > >
> >
> g_staticParams.variableModParameters.cModCode[pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide+1]-1]);
> > > }
> > >
> > > sprintf(szModPep+strlen(szModPep), ".%c",
> > pOutput[iWhichResult].szPrevNextAA[1]);
> > >
> > > fprintf(fpout, "%s\t", szModPep);
> > >
> > > fprintf(fpout, "%s\n", pOutput[iWhichResult].szProtein);
> > > }
> > >
> > > The first part prints the header of Percolator file. The second part
> > > prints the "modified" peptide string that will be only a '*' behind the
> > > modified amino acid.
> > >
> > > thx
> > >
> > > -
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/percolator/percolator/issues/126#issuecomment-104136140
> > >
> > > .
> > >
> >
> > -
> > Reply to this email directly or view it on GitHub<
> >
> https://github.com/percolator/percolator/issues/126#issuecomment-104284513
> > >.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/percolator/percolator/issues/126#issuecomment-104290976
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/percolator/percolator/issues/126#issuecomment-104297285>
> .
>



-- 
========================
Lukas Käll
http://kaell.org

**Comment by thabangh** [comment]
So I am guessing from this response that there isn't any actual
documentation of this file format.  Is that correct?

I will check with Jimmy about switching from the asterisk notation to
bracketed notation in .pin files.  I'll also write a document describing
this file format for inclusion in the Crux documentation.  You can double
check it when it's ready.

Bill

**Comment by thabangh** [comment]
OK, I found this documentation:

https://github.com/percolator/percolator/wiki/Interface

and I expanded it to the attached HTML.  Would you mind reading it over to
check for errors?  It would be great if you could remind me what formulas
you use to compute deltaCn and deltaLCn.

Thanks.
Bill

**Comment by percolator** [comment]
Uh, I did not find the attachment. -L

On Thu, May 21, 2015 at 5:46 PM, thabangh <notifications@github.com> wrote:

> OK, I found this documentation:
>
> https://github.com/percolator/percolator/wiki/Interface
>
> and I expanded it to the attached HTML. Would you mind reading it over to
> check for errors? It would be great if you could remind me what formulas
> you use to compute deltaCn and deltaLCn.
>
> Thanks.
> Bill
>
>
>
> On Thu, May 21, 2015 at 8:25 AM, William S Noble <thabangh@gmail.com>
> wrote:
>
> > So I am guessing from this response that there isn't any actual
> > documentation of this file format. Is that correct?
> >
> > I will check with Jimmy about switching from the asterisk notation to
> > bracketed notation in .pin files. I'll also write a document describing
> > this file format for inclusion in the Crux documentation. You can double
> > check it when it's ready.
> >
> > Bill
> >
> >
> > On Thu, May 21, 2015 at 8:04 AM, Lukas Käll <notifications@github.com>
> > wrote:
> >
> >> Right now percolator interprets any string enclosed by squared brackets
> as
> >> a PTM of the preceding aminoacid. That is you can represent a phospho
> >> tyrosine as T[p], T[+80] or T[UNIMOD:21]. The Unimod notation is
> preferred
> >> as it is an unambiguous notation.
> >>
> >> -Lukas
> >>
> >>
> >>
> >>
> >> On Thu, May 21, 2015 at 4:28 PM, thabangh <notifications@github.com>
> >> wrote:
> >>
> >> > The issue is that a simple mass doesn't tell the whole story. It
> doesn't
> >> > discriminate between static and variable modifications, nor between
> >> normal,
> >> > n-terminal peptide and n-terminal protein mods. But perhaps Lukas can
> >> > weigh in on how he'd like modifications to be represented in the
> >> Percolator
> >> > input format. Is that format documented somewhere?
> >> >
> >> > Bill
> >> >
> >> >
> >> >
> >> > On Thu, May 21, 2015 at 7:14 AM, Fengchao <notifications@github.com>
> >> > wrote:
> >> >
> >> > > I think the best way is adding a mass with brackets to the end of
> >> > modified
> >> > > amino acid. It won't change the column of percolator input file.
> >> > > ________________________________
> >> > > From: thabangh <notifications@github.com>
> >> > > Sent: Thursday, May 21, 2015 9:56:03 PM
> >> > > To: percolator/percolator
> >> > > Cc: Fengchao YU
> >> > > Subject: Re: [percolator] Modification information in Percolator's
> >> > result.
> >> > > (#126)
> >> > >
> >> > >
> >> > > Yes, this is correct. The modification column is only in the
> >> > tab-delimited
> >> > > output format, which is different from the tab-delimited PIN format.
> >> We
> >> > > could ask Jimmy Eng to add this, but I don't know if it would mess
> >> > > Percolator up.
> >> > > Bill
> >> > >
> >> > >
> >> > > On Wed, May 20, 2015 at 10:00 PM, Fengchao <
> notifications@github.com>
> >> > > wrote:
> >> > >
> >> > > > I knew that. But I checked the output and source code again.
> >> percolator
> >> > > > output file don't have this column. Please read the following
> code:
> >> > > >
> >> > > > CometWritePercolator.cpp:
> >> > > >
> >> > > > void CometWritePercolator::WritePercolatorHeader(FILE *fpout)
> >> > > > {
> >> > > > // Write header line
> >> > > > fprintf(fpout, "id\t");
> >> > > > fprintf(fpout, "label\t");
> >> > > > fprintf(fpout, "ScanNr\t");
> >> > > > fprintf(fpout, "lnrSp\t");
> >> > > > fprintf(fpout, "deltLCn\t");
> >> > > > fprintf(fpout, "deltCn\t");
> >> > > > fprintf(fpout, "lnExpect\t");
> >> > > > fprintf(fpout, "Xcorr\t");
> >> > > > fprintf(fpout, "Sp\t");
> >> > > > fprintf(fpout, "IonFrac\t");
> >> > > > fprintf(fpout, "Mass\t");
> >> > > > fprintf(fpout, "PepLen\t");
> >> > > > for (int i=1 ; i<= g_staticParams.options.iMaxPrecursorCharge;
> i++)
> >> > > > fprintf(fpout, "Charge%d\t", i);
> >> > > > fprintf(fpout, "enzN\t");
> >> > > > fprintf(fpout, "enzC\t");
> >> > > > fprintf(fpout, "enzInt\t");
> >> > > > fprintf(fpout, "lnNumSP\t");
> >> > > > fprintf(fpout, "dM\t");
> >> > > > fprintf(fpout, "absdM\t");
> >> > > > fprintf(fpout, "peptide\t");
> >> > > > fprintf(fpout, "proteinId1\n");
> >> > > >
> >> > > > fflush(fpout);
> >> > > > }
> >> > > >
> >> > > > void CometWritePercolator::PrintPercolatorSearchHit(int
> iWhichQuery,
> >> > > > int iWhichResult,
> >> > > > bool bDecoy,
> >> > > > Results *pOutput,
> >> > > > FILE *fpout,
> >> > > > double dDeltaCn,
> >> > > > double dLastDeltaCn)
> >> > > > {
> >> > > > // Something else
> >> > > > // ...
> >> > > >
> >> > > > // construct modified peptide string
> >> > > > char szModPep[512];
> >> > > > szModPep[0]='\0';
> >> > > >
> >> > > > // Write the peptide sequence in the same format as an sqt file.
> >> > > > sprintf(szModPep+strlen(szModPep), "%c.",
> >> > > pOutput[iWhichResult].szPrevNextAA[0]);
> >> > > >
> >> > > > if (g_staticParams.variableModParameters.bVarModSearch
> >> > > > &&
> >> > >
> >> pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide] >
> >> > 0)
> >> > > > {
> >> > > > sprintf(szModPep+strlen(szModPep), "n%c",
> >> > > >
> >> > >
> >> >
> >>
> g_staticParams.variableModParameters.cModCode[pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide]-1]);
> >> > > > }
> >> > > >
> >> > > > for (int i = 0; i<pOutput[iWhichResult].iLenPeptide; i++)
> >> > > > {
> >> > > > sprintf(szModPep+strlen(szModPep), "%c",
> >> > > pOutput[iWhichResult].szPeptide[i]);
> >> > > >
> >> > > > if (g_staticParams.variableModParameters.bVarModSearch
> >> > > > &&
> >> > >
> >> >
> >>
> !isEqual(g_staticParams.variableModParameters.varModList[pOutput[iWhichResult].pcVarModSites[i]-1].dVarModMass,
> >> > > 0.0))
> >> > > > {
> >> > > > sprintf(szModPep+strlen(szModPep), "%c",
> >> > > >
> >> > >
> >> >
> >>
> g_staticParams.variableModParameters.cModCode[pOutput[iWhichResult].pcVarModSites[i]-1]);
> >> > > > }
> >> > > > }
> >> > > >
> >> > > > if (g_staticParams.variableModParameters.bVarModSearch
> >> > > > &&
> >> > >
> >> pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide+1]
> >> > >
> >> > > 1)
> >> > > > {
> >> > > > sprintf(szModPep+strlen(szModPep), "c%c",
> >> > > >
> >> > >
> >> >
> >>
> g_staticParams.variableModParameters.cModCode[pOutput[iWhichResult].pcVarModSites[pOutput[iWhichResult].iLenPeptide+1]-1]);
> >> > > > }
> >> > > >
> >> > > > sprintf(szModPep+strlen(szModPep), ".%c",
> >> > > pOutput[iWhichResult].szPrevNextAA[1]);
> >> > > >
> >> > > > fprintf(fpout, "%s\t", szModPep);
> >> > > >
> >> > > > fprintf(fpout, "%s\n", pOutput[iWhichResult].szProtein);
> >> > > > }
> >> > > >
> >> > > > The first part prints the header of Percolator file. The second
> part
> >> > > > prints the "modified" peptide string that will be only a '*'
> behind
> >> the
> >> > > > modified amino acid.
> >> > > >
> >> > > > thx
> >> > > >
> >> > > > -
> >> > > > Reply to this email directly or view it on GitHub
> >> > > > <
> >> > >
> >> >
> >>
> https://github.com/percolator/percolator/issues/126#issuecomment-104136140
> >> > > >
> >> > > > .
> >> > > >
> >> > >
> >> > > -
> >> > > Reply to this email directly or view it on GitHub<
> >> > >
> >> >
> >>
> https://github.com/percolator/percolator/issues/126#issuecomment-104284513
> >> > > >.
> >> > >
> >> > > —
> >> > > Reply to this email directly or view it on GitHub
> >> > > <
> >> >
> >>
> https://github.com/percolator/percolator/issues/126#issuecomment-104290976
> >> > >
> >> >
> >> > > .
> >> > >
> >> >
> >> > —
> >> > Reply to this email directly or view it on GitHub
> >> > <
> >>
> https://github.com/percolator/percolator/issues/126#issuecomment-104297285
> >> >
> >> > .
> >> >
> >>
> >>
> >>
> >> --
> >> ========================
> >> Lukas Käll
> >> http://kaell.org
> >>
> >> —
> >> Reply to this email directly or view it on GitHub
> >> <
> https://github.com/percolator/percolator/issues/126#issuecomment-104312211
> >
> >> .
> >>
> >
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/percolator/percolator/issues/126#issuecomment-104325756>
> .
>



-- 
========================
Lukas Käll
http://kaell.org

**Comment by thabangh** [comment]
Sorry, I did it by email instead of via the web page, and the attachment got lost.  I don't actually know how to attach an HTML file, so here is a URL:

http://noble.gs.washington.edu/~wnoble/temp/pin-format.html

**Comment by MatthewThe** [comment]
Added information about PTM handling to our own wiki: https://github.com/percolator/percolator/wiki/Post-translational-Modifications-(PTMs)
