### ISSUE TITLE
Option "Description of correct" (flag -D) is non-deterministic

### ISSUE THREAD

**Issue by MatthewThe** [percolator/percolator#129]
Using the Description of correct option contains several calls to `rand()` without a `srand(seed)` anywhere, making it non-deterministic.

Since one of the system tests checks if the number of PSMs is increased by using this flag (and the margin of increase is not that large), the test may fail randomly.

**Comment by percolator** [comment]
Could you change the call so the Scores::lcg_rand() is used instead of rand. That way we get a call that is consistent under the different platforms?
