### ISSUE TITLE
sqt2pin cannot parse PTMs in sqt output from tide-search

### ISSUE THREAD

**Issue by MatthewThe** [percolator/percolator#131]
The output of tide-search (inside the crux toolkit) writes PTMs in the sqt output as `A.PEPT[80]ID.E` (here a phosphorylation), this causes a parsing error in sqt2pin, which expects PTMs to be formatted as `A.PEPT*ID.E` and giving the command line parameter `-p *:21` (the Unimod identifier of phosphorylation is 21).

We can add functionality to also allow mods in the form of `[string]` in sqt format to solve this issue.

Also, static mods are not explicitly named in the tide sqt output (i.e. `A.PEPCID.E` instead of `A.PEPC[57]ID.E`), but are mentioned in one of the header lines as:
```
H       StaticMod       C=160.160
```
We can either keep the convention of leaving out the static mods, or add the mod ourselves.

**Comment by thabangh** [comment]
I don't think you should fix this immediately, as long as the parsing error is handled gracefully.  Tide's handling of modifications will change very soon (I think within a week).  We plan to introduce, like Comet, three columns: an unmodified version of the peptide, a version that contains modifications, and a third column that encodes all of the modification information in an easily parseable format.  I'm not sure what the plan is for SQT, but it would be better to ensure compatibility with Percolator after the new outputs are in place.
