### ISSUE TITLE
Dependency package installation on Fedora20+ and CentOS6+

### ISSUE THREAD

**Issue by MatthewThe** [percolator/percolator#133]
Fedora20+ has the package xerces-c (https://apps.fedoraproject.org/packages/xerces-c) and CentOS6+ has packages for xerces-c, boost 1.41, tokyocabinet and cmake 2.8 (http://mirror.centos.org/centos/6/os/x86_64/Packages/). Installing with yum Instead of compiling from source will greatly speed up the building procedure.

Our own builds are done on Fedora18 and CentOS5 and cannot make use of this, but it is probably good to provide the option for people who want to compile on newer machines.

**Comment by percolator** [comment]
Maybe this is a good time for us to update our target builds to a fresher
version of centos instead of fedora. The reason we used fedora18 was that
it was fresh at the time.

I do not think it is that important to support older versions of Linux.
Den 7 jul 2015 3:48 em skrev "MatthewThe" <notifications@github.com>:

**Comment by sagitter** [comment]
percolator is in Fedora (21+): https://admin.fedoraproject.org/pkgdb/package/percolator/

I'm packaging Percolator-2.10.1 .

**Comment by sagitter** [comment]
Unofficial RPM packages of Percolator for CentOS6/7: http://copr-fe.cloud.fedoraproject.org/coprs/sagitter/percolator-EPEL/

**Comment by percolator** [comment]
Thanks Antonio,

This is helpful

Cheers
-Lukas

On Thu, Oct 1, 2015 at 7:31 PM, Antonio <notifications@github.com> wrote:

> Unofficial RPM packages of Percolator for CentOS6/7:
> http://copr-fe.cloud.fedoraproject.org/coprs/sagitter/percolator-EPEL/
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/percolator/percolator/issues/133#issuecomment-144794529>
> .
>



-- 
========================
Lukas Käll
http://kaell.org

**Comment by sagitter** [comment]
>Unofficial RPM packages of Percolator for CentOS6/7: http://copr-fe.cloud.fedoraproject.org/coprs/sagitter/percolator-EPEL/

These additional repositories have been removed.
Percolator is now built for CentOS6+ and its RPMs are stored in the [EPEL6/7 repositories](https://fedoraproject.org/wiki/EPEL). Please, if someone uses them, leave a + or - feedback:

EPEL7: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-474d533fb5
EPEL6: https://bodhi.fedoraproject.org/updates/FEDORA-EPEL-2015-61a95f4954

**Comment by MatthewThe** [comment]
The build scripts are now changed and tested under CentOS 7.2 and Fedora 23, which are also the systems on which the binary releases for release v3.01 were generated.

Additional dependencies for building on older systems (hints on how to install these dependencies can be found in the [admin/builders folder of branch-3-00](https://github.com/percolator/percolator/tree/branch-3-00/admin/builders)):
* CentOS 6: boost(>=1.46)
* CentOS 5: xerces-c, boost(>=1.46), tokyocabinet and cmake
* Fedora<20: xerces-c

**Comment by sagitter** [comment]
>Additional dependencies for building on older systems (hints on how to install these dependencies can be found in the admin/builders folder of branch-3-00)

I'm rebuild Percolator on Fedora 23+ (Fedora <23 releases are not maintained anymore), EPEL6 and EPEL7 (additional repos for RHEL/CentOS/SL).
I can try to build on EPEL5, too.
