### ISSUE TITLE
msgf2pin crashes on search results with multiple hits per spectrum

### ISSUE THREAD

**Issue by hendrikweisser** [percolator/percolator#136]
msgf2pin crashes with a segmentation fault when I apply it to MS-GF+ results that contain the top 5 hits per query spectrum (MS-GF+ parameter "-n 5"). It works on the same searches when only the single best hit is reported (default setting). This is with the following program versions: "MS-GF+ Beta (v10089) (7/31/2014)" and "Pin-converter version 0.00, Build Date Apr 14 2014 13:22:18".

This may be related to issue #120.

**Comment by MatthewThe** [comment]
The XML validation was previously accidentally circumvented. I made a fix that now outputs validation errors for issues #120 and #121, reporting where in the XML file the errors occur. You can check if this fix helps in your case.

**Comment by hendrikweisser** [comment]
I just tried "msgf2pin" after building it from the current Percolator sources. Unfortunately I now get the following errors, which I think are related to your XML validation changes, on a file that used to work with my previous version:

```
:0:0 warning: unable to open primary document entity '/usr/local/share/percolator/xml-1-1/mzIdentML1.1.0.xsd'
/usr/local/share/percolator/xml-1-1/mzIdentML1.1.0.xsd: error: unable to load
Reading lymph_node_part1.mzid
:0:0 warning: unable to open primary document entity '/usr/local/share/percolator/xml-1-1/mzIdentML1.1.0.xsd'
/usr/local/share/percolator/xml-1-1/mzIdentML1.1.0.xsd: error: unable to load
msgf2pin: /nfs/t17_project/ProteomicsSoftware/Percolator/Source/src/converters/MzidentmlReader.cpp:130: virtual void MzidentmlReader::read(const string&, bool, boost::shared_ptr<FragSpectrumScanDatabase>): Assertion `doc.get()' failed.
Aborted
```

Why does the converter look for the .xsd file in "/usr/local/share" and how can I change that?

**Comment by MatthewThe** [comment]
When the percolator-converters are installed, it should copy the xsd files to the directory specified in `-DCMAKE_INSTALL_PREFIX` with the cmake command (see the build scripts). By default this is `/usr`, though in your case it seems to have been changed to `/usr/local`. It seems that either the files were not copied during installation, or they were installed in a different directory. 

Could you tell me which OS you are using and the steps you took to install from source? Did you by any chance just copy the binaries from the build directory instead of installing the generated package?

**Comment by hendrikweisser** [comment]
I'm on Ubuntu 12.04.

> Did you by any chance just copy the binaries from the build directory instead of installing the generated package?

Yes, exactly. Should I run "make install"?

**Comment by MatthewThe** [comment]
Yes, for the percolator-converters this is necessary.

**Comment by hendrikweisser** [comment]
Okay, thanks. It works now after "make install". (I haven't tested the "multiple hits per spectrum" case, though.)
