### ISSUE TITLE
Installation on a shared Redhat server without sudo, or prefer not to install it at the system level

### ISSUE THREAD

**Issue by wyu** [percolator/percolator#138]
I'd like to install the package on a server that's shared among many users. It makes more sense if I can install it under my own name, rather than "rpm -i" install it at the system level. Is there a way build a static package from the source in another VM, and install it on the server without sudo privilege?

**Comment by MatthewThe** [comment]
This might be possible by setting `CPACK_RPM_PACKAGE_RELOCATABLE` to `TRUE` and `CPACK_SET_DESTDIR` to `FALSE` in CPack.txt.
