### ISSUE TITLE
Percolator sometimes fails to compute PEPs

### ISSUE THREAD

**Issue by hendrikweisser** [percolator/percolator#142]
We have seen cases where Percolator seems to run successfully on a file, but fails to produce PEP values. In such cases all values in the PEP column of a .psms file are 1. This has happened on Mascot search results (via Mascot Percolator) and on MS-GF+ results. According to James Wright, changing the feature set in Mascot Percolator can remedy the problem.

I'm going to attach an example from MS-GF+ that reproducibly exhibits the problem on my machine. I've used the following commands:
```
msgf2pin --pattern XXX_ --outputTab msgf2pin.csv lymph_node_part1.mzid
percolator --only-psms --results percolator_target --decoy-results percolator_decoy msgf2pin.csv
```

**Comment by hendrikweisser** [comment]
Actually, the files are a bit large to upload to a Gist (440 MB .mzid, 40 MB .pin). I can share them e.g. via Google Drive, but would prefer to do so directly with a person (rather than post a publicly accessible link here).

**Comment by hendrikweisser** [comment]
The log from msgf2pin:
```
Pin-converter version 0.00, Build Date Apr 14 2014 13:22:18
Copyright (c) 2013 Lukas Käll. All rights reserved.
Written by Lukas Käll (lukas.kall@scilifelab.se) in the
School of Biotechnology at KTH - Royal Institute of Technology, Stockholm.
Issued command:
msgf2pin --pattern XXX_ --outputTab msgf2pin.csv 005-MSGFPlusAdapter-mzid_out/lymph_node_part1.mzid

Uses features for fragment spectra mass errors
Reading 005-MSGFPlusAdapter-mzid_out/lymph_node_part1.mzid
No scan number was found for a PSM (or it equaled 0), scans are ranked from 1 and up
PSM: SII_42788_1 has feature with value NaN, use the default value for that feature.
PSM: SII_42788_1 has feature with value NaN, use the default value for that feature.
PSM: SII_42788_1 has feature with value NaN, use the default value for that feature.
PSM: SII_42788_1 has feature with value NaN, use the default value for that feature.
PSM: SII_108537_1 has feature with value NaN, use the default value for that feature.
PSM: SII_108537_1 has feature with value NaN, use the default value for that feature.
PSM: SII_108537_1 has feature with value NaN, use the default value for that feature.
PSM: SII_108537_1 has feature with value NaN, use the default value for that feature.
```

And from Percolator:
```
Percolator version 0.00, Build Date Apr 14 2014 13:33:03
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
Issued command:
percolator --only-psms --results percolator_target --decoy-results percolator_decoy msgf2pin.csv
Started Tue Feb 16 11:01:24 2016
Hyperparameters fdr=0.01, Cpos=0, Cneg=0, maxNiter=10
Reading Tab delimited input from datafile msgf2pin.csv
Features:
RawScore DeNovoScore ScoreRatio Energy lnEValue IsotopeError lnExplainedIonCurrentRatio lnNTermIonCurrentRatio lnCTermIonCurrentRatio lnMS2IonCurrent Mass PepLen dM absdM MeanErrorTop7 sqMeanErrorTop7 StdevErrorTop7 Charge2 Charge3 Charge4 Charge5 Charge6 Charge7 Charge8 enzN enzC enzInt
Train/test set contains 85897 positives and 12735 negatives, size ratio=6.74495 and pi0=1
selecting cpos by cross validation
selecting cneg by cross validation
Estimating 54873 over q=0.01 in initial direction
Reading in data and feature calculation took 1.58 cpu seconds or 2 seconds wall time
---Training with Cpos selected by cross validation, Cneg selected by cross validation, fdr=0.01
Iteration 1 :   After the iteration step, 61407 target PSMs with q<0.01 were estimated by cross validation
Iteration 2 :   After the iteration step, 62777 target PSMs with q<0.01 were estimated by cross validation
Iteration 3 :   After the iteration step, 63321 target PSMs with q<0.01 were estimated by cross validation
Iteration 4 :   After the iteration step, 63559 target PSMs with q<0.01 were estimated by cross validation
Iteration 5 :   After the iteration step, 63635 target PSMs with q<0.01 were estimated by cross validation
Iteration 6 :   After the iteration step, 63699 target PSMs with q<0.01 were estimated by cross validation
Iteration 7 :   After the iteration step, 63808 target PSMs with q<0.01 were estimated by cross validation
Iteration 8 :   After the iteration step, 63870 target PSMs with q<0.01 were estimated by cross validation
Iteration 9 :   After the iteration step, 63879 target PSMs with q<0.01 were estimated by cross validation
Iteration 10 :  After the iteration step, 63895 target PSMs with q<0.01 were estimated by cross validation
Obtained weights (only showing weights of first cross validation set)
# first line contains normalized weights, second line the raw weights
RawScore        DeNovoScore     ScoreRatio      Energy  lnEValue        IsotopeError    lnExplainedIonCurrentRatio      lnNTermIonCurrentRatio  lnCTermIonCurrentRatio  lnMS2IonCurrent Mass    PepLen  dM    absdM    MeanErrorTop7   sqMeanErrorTop7 StdevErrorTop7  Charge2 Charge3 Charge4 Charge5 Charge6 Charge7 Charge8 enzN    enzC    enzInt  m0
-0.187  -0.3600 0.0024  -0.1853 4.3397  -0.1793 -0.5154 1.0759  1.0257  -0.0629 1.5521  -0.6343 -0.2382 -0.3695 0.4287  -1.9536 -1.1877 -0.6570 0.3835  0.5720  0.3532  -0.0541 -0.0142 -0.0112 0.2378  0.1253-1.1039  1.5779
-0.0039 -0.0089 0.0000  -0.0062 0.4806  -0.5422 -0.4419 0.4010  0.7368  -0.0411 0.0096  -0.1460 -70797.2936     -151725.3279    0.0091  -0.0029 -0.0250 -1.4477 0.8914  2.9751  4.9336  -1.5798 -1.5781 -1.5781
        1.9662  0.9707  -0.8454 -2.2565
After all training done, 62981 target PSMs with q<0.0100 were found when measuring on the test set
Found 62981 target PSMs scoring over 1.0000% FDR level on testset
Merging results from 3 datasets
Selecting pi_0=0.1545
Calibrating statistics - calculating q values
New pi_0 estimate on merged list gives 71466 PSMs over q=0.0100
Calibrating statistics - calculating Posterior error probabilities (PEPs)
Processing took 110.2 cpu seconds or 110 seconds wall time
```

**Comment by MatthewThe** [comment]
Thank you for reporting this issue, can you share the concerning files with me (`matthew [dot] the [at] scilifelab [dot] se`)?

**Comment by hendrikweisser** [comment]
I've shared the files with you via Google Drive. Did that work?

**Comment by MatthewThe** [comment]
Yes, it worked. Just looking at the data, it seems that the problem could be a decoy PSM with a DeNovoScore of 0, that somehow gets a very high percolator score. I will take a look if this is indeed the problem and how we can fix it.

**Comment by MatthewThe** [comment]
Unfortunately, I cannot reproduce the behaviour on the latest percolator version. I still get the unusually high scoring decoy PSM with the DeNovoScore of 0, but the PEPs seem to be fine. Could you try to remove the decoy PSM `lymph_node_part1_SII_97148_1_105148_2_1` and see if you still get the strange PEP behaviour?

Regardless, we should probably rethink the strategy for calculating the feature `ScoreRatio` (which is the RawScore divided by the DeNovoScore) for the case where the DeNovoScore is 0. Currently, it adds a small float to the DeNovoScore to prevent divide by zero errors, but this created an unusually high feature value for the zero-scoring PSM (-430000, whereas most PSMs have a value for this feature in the range of -2 to +1).

**Comment by hendrikweisser** [comment]
> Could you try to remove the decoy PSM lymph_node_part1_SII_97148_1_105148_2_1 and see if you still get the strange PEP behaviour?

No, removing that PSM solves the problem. :+1:

> Unfortunately, I cannot reproduce the behaviour on the latest percolator version.

Okay, I'll see whether we can update our Percolator installation.

> Regardless, we should probably rethink the strategy for calculating the feature ScoreRatio (which is the RawScore divided by the DeNovoScore) for the case where the DeNovoScore is 0. Currently, it adds a small float to the DeNovoScore to prevent divide by zero errors, but this created an unusually high feature value for the zero-scoring PSM (-430000, whereas most PSMs have a value for this feature in the range of -2 to +1).

Yes, you should probably check if the DeNovoScore is zero, and in that case directly set the ScoreRatio to a meaningful value.

**Comment by hendrikweisser** [comment]
I can confirm that the latest Percolator version from GitHub does not exhibit the bug on our system.
I hope that it might still have been useful for you to look at the example data, because of the "DeNovoScore 0" issue.
Thanks for your help!

**Comment by MatthewThe** [comment]
Alright, good to hear! 
Thanks again for reporting the issue, we will definitely look for an appropriate way to deal with the DeNovoScore = 0 issue.

**Comment by hendrikweisser** [comment]
As far as I'm concerned you could close this issue - unless you want to leave it open for the problem with the unusual ScoreRatio.

**Comment by MatthewThe** [comment]
We will keep it open as a reminder to fix the ScoreRatio issue.

**Comment by hendrikweisser** [comment]
I have now come upon an example (from an MS-GF+ search) where the PEP calculation fails even with the newest Percolator build. Looking at the Percolator input file ("msgf2pin" output), the cause of the problem doesn't seem to be the same as in the previous case, i.e. there is no extreme outlier in the ScoreRatio column.

@MatthewThe, I'm going to share the files with you again via Google Drive. Would be nice if you could have a look.

**Comment by hendrikweisser** [comment]
@MatthewThe: I've shared the files, please let me know whether you got them.

**Comment by MatthewThe** [comment]
Thanks, I have received them now. From a quick look at the data, It might be due to a minor outlier in the ScoreRatio column with id `CHPP_Testis_SDS_2004_SII_28497_1_32520_2_1`, which has a ratio of -46 due to a DeNovoScore of 1. I will give it a run, just to be sure.

We should probably just clip the ScoreRatio at something like -1, I don't think it will majorly impact the performance as these cases are so rare.

**Comment by MatthewThe** [comment]
I can confirm that I got the same PEP=1 behavior on your data. After I clipped the ScoreRatio at -1 in the msgf2pin converter, the PEPs are now calculated correctly on my machine.

**Comment by hendrikweisser** [comment]
I can confirm that it works now. Thanks for the fix!
