### ISSUE TITLE
Windows 64-bit installer

### ISSUE THREAD

**Issue by percolator** [percolator/percolator#144]
Jarrett Egertson reports:
'... the 64-bit version of the installer installs to "Program Files (x86)", which is a bit odd because the standard location for 64-bit binaries on a 64-bit windows system is actually "Program Files".  However, I was able to verify that the binary installed by the 64-bit installer is in fact a 64-bit binary. '

**Comment by MatthewThe** [comment]
This appears to be something CMake has attempted to fix in v2.8.3 and above:

https://cmake.org/gitweb?p=cmake.git;a=commitdiff;h=2f98dac486726c67681ea51a57e19518d7119b1b

https://github.com/Kitware/CMake/commits/master/Modules/Platform/WindowsPaths.cmake

Though I also found a report that it still did not work for v2.8.7:

https://cmake.org/pipermail/cmake/2012-January/048366.html

I will try to build the Windows 64-bit binary using the latest version of CMake and see if that works.
