### ISSUE TITLE
Segmentation fault for Windows 64 and Ubuntu 64

### ISSUE THREAD

**Issue by vsarpe** [percolator/percolator#146]
After installing Win64 version and running the executable without any parameters, the program hangs and windows shuts it down. Trying it on Ubuntu 64, I get a "Segmentation fault".

This also happens with some data files but not with others ("percolator -k")

File which doesn't cause seg fault: [link] (https://www.dropbox.com/s/xsj6onx24alnkia/86c1a11f-e825-4ea5-b119-f0a36768e70d.xml?dl=0)

File which causes seg fault:  [link] (https://www.dropbox.com/s/9lrgsgaxlko03zi/449953c6-d64a-4e0a-95e7-fd7026bff4ee.xml?dl=0)

**Comment by MatthewThe** [comment]
The issue is that some of the flanks are empty, e.g. `flankN=""`. The proper way to handle this case is to set `flankN="-"`. The error message should be made more informative though.

Did you use any of the converters or did you generate the xml file yourself?

**Comment by vsarpe** [comment]
Thanks for the help, I generated the XML myself.
