### ISSUE TITLE
meaning of PSMid after using msgf2pin 

### ISSUE THREAD

**Issue by HonglanLi** [percolator/percolator#147]
Dear everyone, 

I changed MSGF results (*.mzid)  to pin using 'msgf2pin'.

I found that PSMid is hard to understand.

"R1_SII_55_1_2144_2_1"

Does anyone can tell me what exactly these numbers ("55","1", "2144", "2", and "1") mean?

**Comment by MatthewThe** [comment]
Based on the source code (MsgfplusReader.cpp:286) and some closer investigation:

- "R1" is the filename, abbreviated until the first occurence of ".".
- "SII_55_1" is the id given by MSGF, consisting of the spectrum index, "55", and the rank of the hit within the hits for that particular spectrum, "1".
- "2144" is the spectrum's scan number, if available (depends on input format to MSGF). If unavailable, it is the overall rank of the spectrum based on MSGF's E-value.
- "2" is the charge state used for searching.
- "1" is (again) the rank of the hit within the hits for that particular spectrum, which will typically be the same as the last number in the MSGF-id.

**Comment by HonglanLi** [comment]
Thanks a lot:)

**Comment by verheytb** [comment]
I have a follow-up question: with MGF inputs that include scan numbers, is the "2144" in this example a scan number or spectrum rank?

**Comment by MatthewThe** [comment]
If I remember correctly, it's the scan number. When you run `msgf2pin`, do you see this message: 

```No scan number was found for a PSM (or it equaled 0), scans are ranked from 1 and up```

If not, then the "2144" in the example should be the scan number.
