### ISSUE TITLE
Splitting on commas in protein inference engine

### ISSUE THREAD

**Issue by MatthewThe** [percolator/percolator#153]
In the current protein inference code, we represent protein groups by inserting commas between the separate proteins, e.g. `ProteinA1,ProteinA2`. This clearly becomes a problem when the protein names themselves contain commas, e.g. `sp|P53916|TEP1_YEAST Probable phosphatidylinositol 3,4,5-trisphosphate 3-phosphatase TEP1`.

Furthermore, this results in a crash in some cases when Percolator tries to remove the decoy pattern (used for the target-decoy competition in the picked protein FDR calculation) as it splits `decoy_ProteinA,1` into `decoy_ProteinA` and `1`, where the latter segment is too short when we try to remove the pattern `decoy_`. In other cases it might cause undefined behavior.

Possible solutions:
- use the protein group representation we used in Fido, where we only list a single protein per line and instead employ an extra column to indicate which group a protein belongs to. The disadvantage was that it becomes unclear which proteins are in a group when manually going through the file.
- remove/replace commas in protein names prior to protein grouping.
- use a different delimiter than a comma.

**Comment by thabangh** [comment]
On Thu, Jul 21, 2016 at 3:28 AM, MatthewThe <notifications@github.com>
wrote:

> In the current protein inference code, we represent protein groups by
> inserting commas between the separate proteins, e.g. ProteinA1,ProteinA2.
> This clearly becomes a problem when the protein names themselves contain
> commas, e.g. sp|P53916|TEP1_YEAST Probable phosphatidylinositol
> 3,4,5-trisphosphate 3-phosphatase TEP1.
>
> Furthermore, this results in a crash in some cases when Percolator tries
> to remove the decoy pattern (used for the target-decoy competition in the
> picked protein FDR calculation) as it splits decoy_ProteinA,1 into
> decoy_ProteinA and 1, where the latter segment is too short when we try
> to remove the pattern decoy_. In other cases it might cause undefined
> behavior.
>
> Possible solutions:
>
>    - use the protein group representation we used in Fido, where we only
>    list a single protein per line and instead employ an extra column to
>    indicate which group a protein belongs to. The disadvantage was that it
>    becomes unclear which proteins are in a group when manually going through
>    the file.
>    - remove/replace commas in protein names prior to protein grouping.
>    - use a different delimiter than a comma.
>
>
>
I think we should go with option 2, and clearly document the behavior so
the user knows to expect it.  Replacing them with underscores, for example,
seems fair to me.  Option 1 is unwieldy, as you point out. Option 3 doesn't
really solve the problem, because someone will inevitably come up with
protein IDs containing whichever new delimiter we choose.

Bill
