### ISSUE TITLE
msgf2pin fails on C-terminal modifications

### ISSUE THREAD

**Issue by PayamEmami** [percolator/percolator#161]
Hello,
When using msgf2pin converter to prepare MSGFPlus output for Percolator, there will be an error if there is C-terminal modification. The mzIdentML standard says

> Modification to the C-terminus should be given as peptide length + 1

So if we have XXXX amino acid sequence, the location of C-terminal modification must be 5. And, “peptideSeq.insert” is trying to be add the modification at 5th location which will raise an error in string::insert (trying to add the modification in an invalid location):

`std::string FragSpectrumScanDatabase::decoratePeptide(const ::percolatorInNs::peptideType& peptide) {
  std::list<std::pair<int,std::string> > mods;
  std::string peptideSeq = peptide.peptideSequence();
  BOOST_FOREACH (const ::percolatorInNs::modificationType &mod_ref, peptide.modification()) {
    std::stringstream ss;
    if (mod_ref.uniMod().present()) {
      ss << "[UNIMOD:" << mod_ref.uniMod().get().accession() << "]";
      mods.push_back(std::pair<int,std::string>(mod_ref.location(),ss.str()));
    }
    if (mod_ref.freeMod().present()) {
      ss << "[" << mod_ref.freeMod().get().moniker() << "]";
      mods.push_back(std::pair<int,std::string>(mod_ref.location(),ss.str()));
    }
  }
  mods.sort(greater<std::pair<int,std::string> >());
  std::list<std::pair<int,std::string> >::const_iterator it;
  for(it=mods.begin();it!=mods.end();++it) {
    peptideSeq.insert(it->first,it->second);
  }
  return peptideSeq;
}`

It would be great if 

`peptideSeq.insert(it->first,it->second);`

can be changed to something like this: 

`(it->first <= peptideSeq.length()) ? peptideSeq.insert(it->first,it->second) : peptideSeq.insert(peptideSeq.length(),it->second);`

So the C-terminal modification will be always at the end.
Best,
Payam

**Comment by MatthewThe** [comment]
That sounds very reasonable, I will try to implement this and run some tests.
