### ISSUE TITLE
Example documentation confusing

### ISSUE THREAD

**Issue by vuw-ecs-kevin** [percolator/percolator#163]
Hi there,

I am neither a machine learner, nor a shotgun proteomicist, however I had
been asked to install Percolator for someone who is one of those, or perhaps 
might even claim to be both.

As is my wont, I came to try and run a basic "functionality" test of the installtion
and was pointed to the [example page](https://github.com/percolator/percolator/wiki/example) in the project's GitHub Wiki.

Slightly confusingly for me, and possibly others coming new to either field through
the Percolator package, the example suggests that one takes a supplied data set 
and does the following

```
$ sqt2pin -o pin.tab yeast-01.sqt yeast-01.shuffled.sqt 
$ percolator -X pout.xml pin.tab > yeast-01.psms 
```

however, despite believing that I had correctly set the PATH to the newly
installed percolator package's `$prefix\bin` directory, the first command
of that pair didn't work. Deep sorrow.

It would appear that `sqt2pin` is NOT part of the Percolator package, so I,
admittedly not "someone in the field" was wondering if the example could
be altered to either provide data that doesn't require the `sqt2pin` step, or
at least informs folk that, in order to run the example, they'll need to have
installed something else.

--
Kevin M. Buckley

eScience Consultant
School of Engineering and Computer Science
Victoria University of Wellington
New Zealand

**Comment by MatthewThe** [comment]
Thanks for the feedback, this is indeed confusing.

I updated the wiki page to hopefully clarify this issue. In short, `sqt2pin` is part of the percolator-converters package which is present in the release downloads.

**Comment by vuw-ecs-kevin** [comment]
In case you can tailor that clarification a little more, just to say that I was 
building from source (the School is an ArchLinux shop) so it's not a case 
of installing packages, however, I can now see that a simple top-level 
```cmake; make; make install``` doesn't build everything, even though all
the "bits" are in there.
I'm sure I can advise my user as to how to procede now, so thanks for the 
pointers.

**Comment by MatthewThe** [comment]
Alright, I tried to clarify this:

`First, install both the percolator and the percolator-converters package from the latest release (or when building from source, run cmake; make; make install in both the percolator root directory, as well as the src/converters directory).`

Is it clear now?

**Comment by vuw-ecs-kevin** [comment]
That should be enough to point those who have to build from source that one 
needs to run installs in the sub-directories as well, yes.
By the way, whilst ostensibly there for "distro package" building, the scripts
in the ```admin/builders``` directory would appear to have the relevant info,
if you can strip out the distro-specific portions.

FWIW, I actually built our installtion of Percolator and XSD, the requirement
we didn't have for the converters, against a GCC6 and, aside from a couple
of warnings re deprecated stuff and an integer overflow, which I tried to patch,
the test results were identical. If you want, I'll create another issue for that, in 
case it's of some use going forwards.

**Comment by MatthewThe** [comment]
Alright, thanks again for your helpful suggestions!

It would be great if you could inform us about your GCC6 build issues.
