### ISSUE TITLE
Warning when RT and dM columns are missing when using -D flag

### ISSUE THREAD

**Issue by MatthewThe** [percolator/percolator#167]
When the -D option is activated, the two columns after the scannr/label column are expected to contain the retention time and delta mass respectively. However, if these columns are not present, Percolator proceeds by pretending that the first two columns are retention time and delta mass and excludes them from SVM training.

We should check whether the column names correspond to "RT"/"retentionTime" and "dM"/"deltaMass" (probably case insensitive) and issue a warning or even throw an exception and exit immediately (unless the no-terminate flag is activated).

**Comment by cctsou** [comment]
for the column "RT"/"retentionTime", is it absolute RT value? is there option to put DeltaRT?

**Comment by MatthewThe** [comment]
Do you mean that you predicted the retention time yourself and want to supply DeltaRT as a feature? In this case, you can simply provide a normal feature column with your DeltaRT instead, you won't need the `-D` option in this case, nor the extra column for RT and dM (unless you want to use some of the other prediction algorithms from the `-D` option).
