### ISSUE TITLE
zlib1.dll not installed

### ISSUE THREAD

**Issue by wolski** [percolator/percolator#170]
Ist this a feature that percolator for windows is shipped without the zlib1.dll although all executables depend on it? (percolator 3-01)
Windows 8 used installers to install.

Thank you

**Comment by MatthewThe** [comment]
Thanks for reporting this bug. I just checked and zlib1.dll does indeed not get installed with the windows64-bit percolator-converters installer, which it definitely should do. Instead the installer installs zlib1.lib for some reason. I'll look into this.

The windows32-bit percolator-converters installer does install zlib1.dll correctly.
