### ISSUE TITLE
Problems with msgf2pin from release 3.01

### ISSUE THREAD

**Issue by hendrikweisser** [percolator/percolator#178]
I have run into problems with the msgf2pin converter from version 3.01 on two systems, Mac OS X 10.11.6 and Ubuntu 14.04. In both cases, Percolator was installed from the release packages linked on https://github.com/percolator/percolator/releases. I'm testing it on an MS-GF+ mzid file that worked with an earlier build (from source, April 2016) on the Ubuntu system.

On Mac OS X, the converter prints the following message, but produces only an empty output file.
```
Pin-converter version 3.01, Build Date Nov 16 2016 18:41:39
Copyright (c) 2013 Lukas Käll. All rights reserved.
Written by Lukas Käll (lukas.kall@scilifelab.se) in the
School of Biotechnology at KTH - Royal Institute of Technology, Stockholm.
Issued command:
msgf2pin -o test.pin -P XXX_ -v 5 CHPP_SDS_3001.mzid

MzIdentML - MSGF+ format
Uses features for fragment spectra mass errors
```

On the Ubuntu system, the converter fails with the following error:
```
XML parser warning at :0:0
  warning: unable to open primary document entity '/usr/share/percolator/xml-1-1/mzIdentML1.1.0.xsd'
/usr/share/percolator/xml-1-1/mzIdentML1.1.0.xsd: error: unable to load
Reading CHPP_SDS_3001.mzid
XML parser warning at :0:0
  warning: unable to open primary document entity '/usr/share/percolator/xml-1-1/mzIdentML1.1.0.xsd'
/usr/share/percolator/xml-1-1/mzIdentML1.1.0.xsd: error: unable to load
Segmentation fault
```

The `/usr/share/percolator` directory does not exist and I don't have the necessary rights to create it. `share/percolator/xml-1-1/mzIdentML1.1.0.xsd` does exist in the Percolator install directory, so I assume it's a bug in the package build process that leads to the converter looking in the wrong place. (Alternatively, being able to pass the path to the XSD via a command line argument would also work.)

**Comment by MatthewThe** [comment]
We haven't done much testing with non-sudo installations, but from your description and suggestion, it should probably be possible on Ubuntu. I'll see if I can make it work. When you say it worked with an earlier build, did you have the appropriate rights to create files in /usr/share back then?

We have been struggling a bit with the converters on OSX (#76), resorting to a temporary fix for temporary files. Maybe something is going wrong with file permissions, but I'll see if I can reproduce it.

**Comment by hendrikweisser** [comment]
Thanks for looking into this.

> When you say it worked with an earlier build, did you have the appropriate rights to create files in /usr/share back then?

No, it worked with a local installation.

> We have been struggling a bit with the converters on OSX (#76), resorting to a temporary fix for temporary files. Maybe something is going wrong with file permissions, but I'll see if I can reproduce it.

So msgf2pin needs to create temporary files? It's not a problem with permissions for the output file, as that gets created successfully (but without content).

**Comment by hendrikweisser** [comment]
On Linux, the problem also affects the converter for X! Tandem, tandem2pin. The error message in that case is:
```
XML parser warning at :0:0
  warning: unable to open primary document entity '/usr/share/percolator/xml-2011.12.01.1/tandem2011.12.01.1.xsd'
/usr/share/percolator/xml-2011.12.01.1/tandem2011.12.01.1.xsd: error: unable to load
```

**Comment by MatthewThe** [comment]
The issue with empty output file on MacOS should be fixed now. The second issue with tandem2pin not being to able to find the xsd file might still persist, but I will create a new issue for that as it does not relate to the original issue.
