### ISSUE TITLE
cannot find an initial direction with positive training examples

### ISSUE THREAD

**Issue by animesh** [percolator/percolator#179]
Dear Developers,

I am trying to run percolator v3.1 over the pin output from comet 201612 version using windows 64 bit version. However I am facing following error  when i run [130319_LINDA_K18_test-comdecoyqe.txt](https://github.com/percolator/percolator/files/813956/130319_LINDA_K18_test-comdecoyqe.txt)
using percolator via command line:

```
percolator\percolator-v3-01\bin\percolator.exe 130319_LINDA_K18_test-comdecoyqe.pin
Percolator version 3.01, Build Date Nov 16 2016 08:44:38
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas K├ñll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
Issued command:
f:\promec\percolator\percolator-v3-01\bin\percolator.exe 130319_LINDA_K18_test-c
omdecoyqe.pin
Started Thu Mar 02 14:47:27 2017
Hyperparameters: selectionFdr=0.01, Cpos=0, Cneg=0, maxNiter=10
Reading tab-delimited input from datafile 130319_LINDA_K18_test-comdecoyqe.pin
Features:
lnrSp deltLCn deltCn lnExpect Xcorr Sp IonFrac Mass PepLen Charge1 Charge2 Charg
e3 Charge4 Charge5 Charge6 enzN enzC enzInt lnNumSP dM absdM
Found 885 PSMs
Separate target and decoy search inputs detected, using mix-max method.
Train/test set contains 452 positives and 433 negatives, size ratio=1.04388 and
pi0=1
Selecting Cpos by cross-validation.
Selecting Cneg by cross-validation.
Split 1:        Exception caught: Error in the input data: cannot find an initia
l direction with positive training examples. Consider raising the training FDR t
hreshold (-F flag).
Terminating.
```

Could you check the input file and let me know if this is an issue with the input format or number of examples are not enough? I have tried wild -F values such as 0 and 1 with same error.

Best regards,

Ani

**Comment by MatthewThe** [comment]
As far as I can tell, your input is valid. The problem indeed seems to be that you do not have enough samples, or more specifically not enough true hits. If you have the option to get more data, this is your best bet.

We have made some adjustments in the master branch (not released yet) that will at least attempt to do some training, but this still won't give you any significant hits at acceptable q-value thresholds.

**Comment by animesh** [comment]
Thanks Matthew for quickly looking into this :) Just wondering what is the typical number of 1 and -1 hits required for training? Also what is the reason not to have any output even when -F is raised to 1?

**Comment by MatthewThe** [comment]
I would say that a few thousand target and decoy, maybe about 5000 each, would constitute a typical minimum run. Often we even combine multiple runs from one experiment in one percolator run.

It's still a bit tricky to say, since it actually rather depends on how many *correct* PSMs there are, e.g. if your experimental set-up is such that you expect very few true hits to your database, 5000 target PSMs might still not be enough if you only expect 50 of those to be correct.

**Comment by animesh** [comment]
OK :+1: I tried with wider precursor threshold comet search which creates roughly 5000  +1 and -1 marked hits 
[130319_LINDA_K18_test-comdecoyqewide.txt](https://github.com/percolator/percolator/files/816371/130319_LINDA_K18_test-comdecoyqewide.txt) and ran percolator with -F 1, 

```
percolator\percolator-v3-01\bin\percolator.exe -F 1 130319_LINDA_K18_test-comdecoyqewide.tsv
Percolator version 3.01, Build Date Nov 16 2016 08:44:38
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas K├ñll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
Issued command:
f:\promec\percolator\percolator-v3-01\bin\percolator.exe -F 1 130319_LINDA_K18_t
est-comdecoyqewide.tsv
Started Fri Mar 03 10:32:38 2017
Hyperparameters: selectionFdr=1, Cpos=0, Cneg=0, maxNiter=10
Reading tab-delimited input from datafile 130319_LINDA_K18_test-comdecoyqewide.t
sv
Features:
lnrSp deltLCn deltCn lnExpect Xcorr Sp IonFrac Mass PepLen Charge1 Charge2 Charg
e3 Charge4 Charge5 Charge6 enzN enzC enzInt lnNumSP dM absdM
Found 8947 PSMs
Separate target and decoy search inputs detected, using mix-max method.
Train/test set contains 4454 positives and 4493 negatives, size ratio=0.99132 an
d pi0=1
Selecting Cpos by cross-validation.
Selecting Cneg by cross-validation.
Split 1:        Exception caught: Error in the input data: cannot find an initia
l direction with positive training examples. Consider raising the training FDR t
hreshold (-F flag).
Terminating.
```

still i don't see an output :( The way i understand -F switch is that 1 means 100% FDR, so i thought percolator files will output the PSM with their FDR even if it is ridiculously high as might be the case in this example? Or it simply ignores the file if it is unable to find things with some inbuilt threshold governed by True/False hits ratio? If that is the case, is there some other switch to override and run the program in anycase even though the results will be ridiculous :)

**Comment by MatthewThe** [comment]
Hmm, yes you are completely right about the -F flag. For some reason we are using the testing FDR (-t flag) in that part of the code, so the error message is very misleading.. I'll fix this.

There are two things you could try out for the moment:
- Use percolator v3.0, which has not implemented the stricter FDR calculation of v3.1
- Set both the -F and -t flags (the testing FDR) to a higher value; looking at your data, something like 0.1 should work already.

**Comment by animesh** [comment]
Thanks again for the clarification Matthew, -t 0.17 worked :+1:  

BTW, what is the usual recommendation for the Percolator, concatenated target-decoy search or search separately and combine with +1 and -1 columns respectively?

**Comment by MatthewThe** [comment]
Great to hear that it works now.

Both methods work about equally well I think, though for particular settings one might outperform the other by a few percent. I tend to prefer separate searches in my own pipelines, since you can always do a target-decoy competition (-Y flag) in percolator to emulate a concatenated search.

**Comment by talpa25** [comment]
Dear Developers,

i have the same issue using Percolator 3.01 for x64 Windows on the output from the Kojak Crosslink Massspec software. 
[20170809_4XL_250mM_mE_ara_BMOE2.perc.inter.txt](https://github.com/percolator/percolator/files/1224632/20170809_4XL_250mM_mE_ara_BMOE2.perc.inter.txt)
Could you plz have a look, whether i have a chance to validate this output with percolator. I'm not sure, whether Kojak gives the data in the right format, but it suggests to run this output file like this: http://www.kojak-ms.org/docs/validation.html

Thanx in advance

**Comment by talpa25** [comment]
P.S.: The Decoys are tagged as "Reversed"

**Comment by javanOkendo** [comment]
Sorry to reopen this, 
I sm also getting the same error and I do not know how to go about it
An exception occurred: Error in the input data: cannot find an initial direction with positive training examples. Consider setting/raising the initial training FDR threshold (--train-initial-fdr).
Terminating.
