### ISSUE TITLE
X! Tandem output file not recognized by converter

### ISSUE THREAD

**Issue by hendrikweisser** [percolator/percolator#180]
The tandem2pin converter tests for the presence of the string "tandem" in the second line of its input file. This line usually contains this:
`<?xml-stylesheet type="text/xsl" href="tandem-style.xsl"?>` 

If the test fails, a warning message is written:
`XML file not generated by X!tandem: [filename]`

However, this line is only written by X! Tandem if the "output, xsl path" parameter is set in the configuration (see http://www.thegpm.org/TANDEM/api/oxp.html), which is optional. The XSL path/filename doesn't necessarily contain the word "tandem", either. So a perfectly valid X! Tandem output file may fail the test.

This is only a minor issue, since processing continues even if the validity check failed. However, it may still be confusing for users.

**Comment by MatthewThe** [comment]
This indeed seems like a too simplistic test. 

I'm not too well-versed in the X! Tandem output format, but would it be enough to check if there is a bioml tag present to ensure the input came from X! Tandem? Alternatively, could you provide the first few lines of your XML file generated without setting the xsl path?

**Comment by hendrikweisser** [comment]
> I'm not too well-versed in the X! Tandem output format, but would it be enough to check if there is a bioml tag present to ensure the input came from X! Tandem?

Yes, that should be enough. Since X! Tandem doesn't define it's own XML schema, you can't do much more than check for BIOML.
