### ISSUE TITLE
X! Tandem converter loses modification information

### ISSUE THREAD

**Issue by hendrikweisser** [percolator/percolator#182]
The converter for X! Tandem results, tandem2pin, does not carry over sequence modifications (PTMs) into its output. That means this information is lost when Percolator results are used for further processing.

This is in contrast to the MS-GF+ converter, msgf2pin, which preserves modifications. The different behaviours make it difficult to compare/combine results from MS-GF+ and X! Tandem after Percolator analysis.

**Comment by MatthewThe** [comment]
Hmm, this should have been fixed already (#132) and it seems to work in my local install. Could you send/attach your tandem xml file where the modifications do not get carried over?

**Comment by hendrikweisser** [comment]
Oh, my bad, I used an older Percolator version. Unfortunately I can't test it with the latest one due to #178.
I'm going to close this.
