### ISSUE TITLE
No error message if output directory does not exist

### ISSUE THREAD

**Issue by wsnoble** [percolator/percolator#185]
If you run percolator and ask (via, e.g., the --results-peptides flag) the program to produce output files in a directory that does not exist, it will happily run to completion but produce no output at all. It seems like Percolator should notice that it can't produce the requested output files and exit with an error message.

**Comment by MatthewThe** [comment]
While I'm not aware of a cross-platform way to check if the output directory exists (we use boost::filesystem in the converters package, but we are trying to avoid that dependency in the main package), it should definitely be possible to check if the output file was created successfully. I will try to implement this check.
