### ISSUE TITLE
X! Tandem converter crashes on "-nan" value

### ISSUE THREAD

**Issue by hendrikweisser** [percolator/percolator#187]
The X! Tandem converter (tandem2pin) crashes on an input file (X! Tandem result) with the following line:

`<protein expect="-nan" id="4.3" uid="4002272" label="UniProt_P13645 K1C10_HUMAN Icytoskeletal10OS=HomosapiensGN=KRT10PE=1SV=6" sumI="6.95" >`

This is the error message:
```
XML parser error at /tmp/2017-04-21_110605_ebi5-188.ebi.ac.uk_26192_1/TOPPAS_tmp/proteogenomics_ebi_3/007_XTandemAdapter/xml_out/CHPP_SDS_3003.unknown:112:156
  error: invalid character encountered
```

I'm pretty sure it's the "-nan" in the protein E-value that causes the problem.
Could you add a special case for this in the code?

**Comment by BioWu** [comment]
@hendrikweisser Hello! Have solved this problem?
I met it too, and I wonder if this caused by The version of X!Tandem (Alanine) or others.
Thanks!

**Comment by MatthewThe** [comment]
Unfortunately, the error is raised by our XML parsing library (XercesC), so we cannot catch this case without some significant hacking.

Also a `-nan` value does not make much sense, valid values are `-INF`, `INF` and `NaN` (e.g. see https://www.working-software.com/cpp-floats-as-decimal, capitalization matters), which all seem to work with our parser. This is something the X!Tandem developers should solve.
