### ISSUE TITLE
Ubuntu 16.04: XercesC dependency on ICU library

### ISSUE THREAD

**Issue by MatthewThe** [percolator/percolator#188]
The XercesC library installed by apt-get in Ubuntu 16.04 currently contains a dependency on the ICU (unicode) library (XercesC: v3.1.3). This causes the ubuntu build script to fail with "undefined references ..." to this library.

As Percolator probably does not need this dependency (and the ICU library itself has some dependencies as well), the best solution is to build XercesC from source again in the ubuntu install script, without this dependency.

**Comment by MatthewThe** [comment]
The installation script on the master branch should already contain the workaround proposed here, but it is not extensively tested yet. Can you check if your build folder contains a folder called `xerces-c-3.1.4`?

**Comment by MatthewThe** [comment]
The suggested fix breaks the Travis build for non Ubuntu 16.04, more testing needed.

**Comment by hsiaoyi0504** [comment]
Is there any update of this ?

**Comment by hsiaoyi0504** [comment]
It looks like I have a similar issue, but I install the percolator without using the helper scripts.

**Comment by MatthewThe** [comment]
Have you tried compiling Xerces with the flags `--disable-netaccessor-curl --disable-transcoder-icu` as in the builder script: https://github.com/percolator/percolator/blob/71e96e0fead2fe9e058a10b4f7bb4204c2334edd/admin/builders/ubuntu64_build.sh#L60-L66

**Comment by mrForce** [comment]
Hey, sorry to dig up an old thread, but the current URL for ${ubuntu_xerces} (http://apache.mirrors.spacedump.net/xerces/c/3/sources/xerces-c-3.2.2.tar.gz) in _urls_and_file_names.sh gives a 404 error. It looks like you have to change it to http://apache.mirrors.spacedump.net/xerces/c/3/sources/xerces-c-3.2.3.tar.gz

**Comment by MatthewThe** [comment]
Thanks! I'll update the package URL.

**Comment by percolator** [comment]
The same concern is valid for centos 8
