### ISSUE TITLE
Big RAM consumption of Percolator during Protein inference

### ISSUE THREAD

**Issue by percolator** [percolator/percolator#191]
Vladimir Gorshkov wrote:

We have talked at the bioinformatics hub about a possible bug in the Percolator. I have prepared the example files (there are FASTA database and Input file in percolator format created by msgf2pin) since they are quite large I have uploaded them to our university server, you can access them via the following link 
https://filesender.deic.dk/filesender/?vid=5fbd9e65-1db9-2549-db8d-000055e3d1d8 

The resulting memory consumption is ~70 Gb.
 
The percolator itself is used as follows:
percolator -Y -c -g -P DECOY_ -f uniprot-human+cow+decoy.fasta -z trypsin -X AstroSecretome.pout.xml AstroSecretome.pin > AstroSecretome.pout
 
Thank you in advance.

**Comment by MatthewThe** [comment]
The trypsin cleavage in MSGF+ is actually trypsin/p, changing `-z trypsin` to `-z trypsinp` will probably already perform much better. Perhaps we should make this part of the checks we do now for number of miscleavages and non-enzymatic ends.
