### ISSUE TITLE
combined input files for validation

### ISSUE THREAD

**Issue by why2kill** [percolator/percolator#192]
Hello,

If I have some files of search result, maybe from different search engines, different qualities, different fractions.
To validate them at a time, can I just concatenate all the files into one file as the input?
It seems that the version in crux has the command "--list-of-files", but not in Percolator3.0 .
Thus, I wonder if combining multiple files artificially by myself is the way Percolator doing this.
Thanks.
Wang, J.H.

**Comment by MatthewThe** [comment]
It will be difficult to combine input files from different search engines, as they will most likely not contain the same features.

For different fractions (and qualities as well, though this is not recommended) you can combine several runs using the converters, e.g. from the help text of sqt2pin:

> Small data sets may be merged by replace the sqt-files with
meta files. Meta files are text files containing the paths of sqt-files, one
path per line. For successful result, the different runs should be generated
under similar condition.

**Comment by why2kill** [comment]
Thanks for MattherThe's reply.
Because the converters currently support 3 data types: tandem, msgf and sqt,
 there might be a problem for other format since I've been developing a new search engine which outputs search-result in .pep.xml or a .tab file(one PSM per row).
The .tab file is easy adjusting into the .tab file for Percolator to perform validation on my search-result .
So I more want to know what's the suggestion about dealing with multiple .tab.
It looks easier for my process.

**Comment by MatthewThe** [comment]
I'm not entirely sure what your question is, but you can simply concatenate (removing the headers of all but the first file) several .tab files, as long as they contain the same columns.
