### ISSUE TITLE
macOS installer incompatibility with macOS 10.11+

### ISSUE THREAD

**Issue by MatthewThe** [percolator/percolator#193]
The macOS installers currently fail on macOS Sierra with the following message:

> This package is incompatible with this version of macOS and may fail to install.

One can choose to continue anyway, but this does not work either.

Apparently Apple changed their permissions for installers starting from macOS 10.11 (El Capitan), not allowing access to the /usr folder (https://github.com/Benjamin-Dobell/Heimdall/issues/336). The solution is to install to /usr/local instead.

We can easily change this in the building scripts by changing the -DCMAKE_INSTALL_PREFIX CMake command line argument, but we will need to rebuild all packages for the binary releases.

**Comment by Lucasjh** [comment]
I'm trying to root my phone and I got the same problem while installing heimdall in Sierra. I found this and it worked!: https://forum.xda-developers.com/tab-s2/general/guide-how-to-jodin3-osx-el-capitan-t3393606

**Comment by rradillen** [comment]
same thing here: useless on macosx for now

**Comment by arctouch-dartagnanribeiro** [comment]
> I'm trying to root my phone and I got the same problem while installing heimdall in Sierra. I found this and it worked!: https://forum.xda-developers.com/tab-s2/general/guide-how-to-jodin3-osx-el-capitan-t3393606

Thanks @Lucasjh
