### ISSUE TITLE
tandem2pin cannot find xsd file

### ISSUE THREAD

**Issue by MatthewThe** [percolator/percolator#196]
@hendrikweisser: On Linux, there is a problem for the X! Tandem converter, tandem2pin. The error message in that case is:
```
XML parser warning at :0:0
  warning: unable to open primary document entity '/usr/share/percolator/xml-2011.12.01.1/tandem2011.12.01.1.xsd'
/usr/share/percolator/xml-2011.12.01.1/tandem2011.12.01.1.xsd: error: unable to load
```

**Comment by BioWu** [comment]
@MatthewThe Hello! Have solved this problem?
I met it too, and I wonder if this caused by The version of X!Tandem (Alanine) or others. 
Thanks!

**Comment by MatthewThe** [comment]
This was simply a matter of running `sudo make install` after building from source.
