### ISSUE TITLE
msgf2pin - "decoy" vs "target"

### ISSUE THREAD

**Issue by meilumcdermott** [percolator/percolator#199]
Running the msgf2pin converter:

`
msgf2pin -o output3.pin -v 5 -F uniprot_sprot.fasta,uniprot_sprot_decoy.fasta firsttest.mzid firsttest_decoy.mzid
`

Has the output:

> mmcdermott:percolator-converters mmcdermott$ msgf2pin -o output.pin -v 5 -F uniprot_sprot.fasta,uniprot_sprot_decoy.fasta firsttest.mzid firsttest_decoy.mzid
> 
> Pin-converter version 3.01, Build Date Jul 31 2017 10:54:49
> Copyright (c) 2013 Lukas Käll. All rights reserved.
> Written by Lukas Käll (lukas.kall@scilifelab.se) in the
> School of Biotechnology at KTH - Royal Institute of Technology, Stockholm.
> Issued command:
> msgf2pin -o output.pin -v 5 -F uniprot_sprot.fasta,uniprot_sprot_decoy.fasta firsttest.mzid firsttest_decoy.mzid
> 
> Reading fasta file : uniprot_sprot.fasta
> 
> Read 555594decoy proteins
> 
> Reading fasta file : uniprot_sprot_decoy.fasta
> 
> Read 1111188target proteins
> 
> MzIdentML - MSGF+ format
> Uses features for fragment spectra mass errors
> MzIdentML - MSGF+ format
> Reading firsttest.mzid
> Reading firsttest_decoy.mzid
> 
> The output will be written to output.pin
> 
> Writing output:
> Databases : 1

The msgf2pin -h documentation says that it should be formatted as target.fasta,[decoy.fasta] but it seems that it's reading them in the opposite way - or is it just the printout that is switched?

**Comment by MatthewThe** [comment]
The print out is just switched around, it is reading in the targets first and decoys second.
