### ISSUE TITLE
Fido Protein Inference not providing proper grouping?

### ISSUE THREAD

**Issue by thinkle12** [percolator/percolator#201]
I have been attempting to use the Fido protein inference tool.
Here is my percolator input file:
[Bioplex_b6352_QLPALL_PEG10_109691_perc_input_no_rank.txt](https://github.com/percolator/percolator/files/1423170/Bioplex_b6352_QLPALL_PEG10_109691_perc_input_no_rank.txt)

I run the command:
percolator Bioplex_b6352_QLPALL_PEG10_109691_perc_input_no_rank.txt -A -P "##" -l fido_test_out.txt -L fido_test_decoy_out.txt

The output files:
[fido_test_out.txt](https://github.com/percolator/percolator/files/1423153/fido_test_out.txt)
[fido_test_decoy_out.txt](https://github.com/percolator/percolator/files/1423154/fido_test_decoy_out.txt)

As we can see in fido_test_out.txt, there seems to be no grouping happenning. Essentially, proteins with identical matching peptides are assigned different ProteinGroupId numbers. 

Is this output expected?

Thank you for your time.

Trent

**Comment by MatthewThe** [comment]
This is not the expected behavior, I will take a look at it.

**Comment by thinkle12** [comment]
Great, please let me know what you can find out.

**Comment by MatthewThe** [comment]
There was indeed a bug in the generation of the protein group ids. I think the bug should be fixed now, do you need a binary distribution, or can you build it yourself from the current master branch?

**Comment by thinkle12** [comment]
I have been using the the osx version. Will I need to build it myself from the master branch? I can attempt that.

**Comment by MatthewThe** [comment]
Please try to build it from the master branch. If it does not work out for some reason, I can build it for you and send you the binaries.
