### ISSUE TITLE
Percolator produces slightly different results under Win10 and ubuntu 16.04

### ISSUE THREAD

**Issue by fcyu** [percolator/percolator#203]
Hi,

For the fist dataset, there are more than 5000 significant PSMs. Percolator produces two slightly different results in terms of the number of PSMs <= 0.01 (5687 vs 5729) and the orders of PSMs. 

For the second dataset, there are only about 100 significant PSMs although there are more than 30000 MS2 spectra in total. Percolator produces two different results (110 vs 0). There are actually some highly scored PSMs with xcorr > 4 ("score" column in the percolator input file). Under Ubuntu, these PSMs are re-ordered to the bottom. Under Win, these PSMs are re-ordered to the top.

I guess this may due to the randomness in the training and cross-validation steps (and maybe slightly difference in terms of the float point precision). But it is quite strange to see different results with the same input. Could you please somehow fix this?

I put my input file, output files, and log files in the attachment.

Thanks

[dataset1.zip](https://github.com/percolator/percolator/files/1596797/dataset1.zip)
[dataset2.zip](https://github.com/percolator/percolator/files/1596798/dataset2.zip)

**Comment by MatthewThe** [comment]
This issue is most likely resolved by the latest commit 2f4e2a6beffe19cfc392a7cf1a8e4f87264373bc . We will probably come out with a new release soon which incorporates this fix, in the meantime you could try to build this from source.

**Comment by fcyu** [comment]
[build.log](https://github.com/percolator/percolator/files/1599214/build.log)
@MatthewThe thanks for your reply. 

I built Percolator in Win10 and re-ran the tests. For dataset1, the numbers became 5744 vs 5729. For dataset2 the numbers 259 vs 0. I put all files in the attachment. 

BTW, I tried to build Percolator in Ubuntu but there are errors. I also put the log in the attachment.

Thanks
[dataset1.zip](https://github.com/percolator/percolator/files/1599212/dataset1.zip)
[dataset2.zip](https://github.com/percolator/percolator/files/1599213/dataset2.zip)

**Comment by MatthewThe** [comment]
The ubuntu build error is probably the same as issue #188 . You might have to run lines 60-66 in the `admin/builders/ubuntu64_build.sh` manually.

I ran your data sets with my own latest build on ubuntu and it produces 5744 and 259 for dataset1 and dataset2 respectively, so that matches with your latest windows build, right?

**Comment by fcyu** [comment]
If I was correct, variable "ubuntu_xerces" was not defined in the ubuntu64_build.sh. I manually downloaded xerces-c from [http://xerces.apache.org/xerces-c/download.cgi](http://xerces.apache.org/xerces-c/download.cgi) and built it. 

I also tested those two datasets and the results are consistent in two plantforms now.

Cheers.

**Comment by MatthewThe** [comment]
Ah sorry, yes, ubuntu_xerces is defined in an external file (`admin/builders/_urls_and_file_names_.sh`). Great to hear that you obtain the same results now!
