### ISSUE TITLE
PIN file label column vs --protein-decoy-pattern option

### ISSUE THREAD

**Issue by Curley-Joe** [percolator/percolator#205]
Percolator version 3.01 seems to rely on the PIN file's label column instead of using the value of the --protein-decoy-pattern option.  This causes problems if the label column is wrong, which is the case with the latest version of Comet.

**Comment by MatthewThe** [comment]
Did you use the `sqt2pin` converter to generate the PIN file? There is an option `--pattern` which will decide the label.

Inside the main percolator executable, the `--protein-decoy-pattern` option is only meant for the picked-protein strategy which only keeps the higher scoring protein of each target-decoy protein pair.

**Comment by Curley-Joe** [comment]
I used percolator, not sqt2pin.  

The descriptions for --pattern and --protein-decoy-pattern are almost identical, and --picked-protein doesn't mention anything about --protein-decoy-pattern, so maybe you can update the documentation to make it more clear.

**Comment by MatthewThe** [comment]
That is indeed confusing, I will update the documentation.

Regarding your initial problem, I guess this is a bug in Comet rather than in Percolator, or do you foresee any changes we could make to solve this?

**Comment by Curley-Joe** [comment]
Oh, sorry I forgot to mention that I contacted the Comet author and he fixed the problem.
