### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by stefanks** [percolator/percolator#206]
Percolator gives different results for different scan numbers: i.e. if I shuffle the scan numbers in the input tsv file, the resulting ranking in the output xml is different, in a sense that different peptides are now ranked higher than in the unshuffled list.

**Comment by MatthewThe** [comment]
The scan numbers are used in two places: 1. to make sure that PSMs from the same spectrum end up in the same cross validation bin and 2. to eliminate one out of each scan number target-decoy pair if target-decoy competition is employed. These effects could cause the ordering to change, though it should generally not affect the rank of significant peptides too much.

Could you provide us with some example files and the command you used?

**Comment by stefanks** [comment]
We detect co-isolated peptides, meaning there are multiple peptides matched to a single spectrum. Is this want you mean by "PSMs from the same spectrum"? It shouldn't be an issue then, since if I only switch two scan numbers where both appear exactly once, I still get different ranking. We do not use target-decoy competition. 

I was running this command:  
```
.\percolator.exe -X pout.xml -m poutpsms.tsv -Z -w finalWeights.txt -U forPercolator.tsv
```

I'll try to come up with a minimal example.

**Comment by stefanks** [comment]
Two tsv files are here:
https://uwmadison.box.com/s/i7uuz6lb4ov1b9w31ng4gnicxur9cuwe

They are different in one thing: scan numbers for psms 6 and 10 are switched. 

The resulting psm-level tsv outputs have wildly different scores for those psms. What could be the explanation? Thanks!

**Comment by MatthewThe** [comment]
I indeed meant co-isolated peptides, but as you pointed out that should not be an issue in your case.

I tested your files, it does indeed give slightly different results, but as far as I can see the q-values and PEPs are still very similar. The SVM scores change around a bit more, but one cannot really interpret these in absolute terms anyway. 

Which version of percolator are you using, and could you maybe upload the results files + output logs as well?

**Comment by stefanks** [comment]
Using the current version of percolator, 3.01

What concerns me is that there are two features, F1 are both 33, and F2 is higher in the 6th psm than in the 10th, so there should not be any reason for re-ranking those!

I placed the files in the same folder

**Comment by MatthewThe** [comment]
Thanks for the files, they are indeed the same results I obtained. I see your point and as far as I can tell the ranking is restored on the latest master branch (we will hopefully create a new release soon), most likely due to a minor bug fix concerning the random number generation on windows.

However, generally one should not focus too much on the exact ranking, but rather on the q-values and PEPs. The re-ranking can easily occur due to different seeds to the random number generation, which determines the division over the cross validation bins. You can see this when changing the seed, e.g. adding the flag '-S 123' to your command.

**Comment by stefanks** [comment]
I am still unsure how it is possible that after some re-ranking psm 10 (with F1=33, F2=0.2) is ranked higher than psm 6 (with F1=33, F3=0.3).  All feature values are either same or better in psm 6 !

**Comment by MatthewThe** [comment]
There are actually three scoring vectors, one for each cross validation bin and each PSM is only scored by one of them (the one in which it was not used as a training sample). Also, we use a scheme to normalize the scores from each of the cross validation bins, before the results are combined in a single list. It is most likely the effect of the latter you are observing here.

**Comment by stefanks** [comment]
Oh, okay! Makes sense, thank you.l
