### ISSUE TITLE
Error in the input data: cannot find an initial direction with positive training examples

### ISSUE THREAD

**Issue by MinHuang0129** [percolator/percolator#208]
Dear developer,
   I used percolator in TPP to validate PSMs after Kojak search. ''Intra.txt" can successfully be validated, but the other txt "Inter.txt" FAILED.
"Split 1:	Exception caught: Error in the input data: cannot find an initial direction with positive training examples. Consider raising the training FDR threshold (-F flag).
Terminating."
   These two txt files were both generated after Kojak search by TPP, so I'm confused why is this happening and what should I do?
   I attached the two files here, hope to GET YOUR HELP, thanks a lot.
[Q_2013_1016_RJ_09.perc.inter.txt](https://github.com/percolator/percolator/files/1684009/Q_2013_1016_RJ_09.perc.inter.txt)
[Q_2013_1016_RJ_09.perc.intra.txt](https://github.com/percolator/percolator/files/1684010/Q_2013_1016_RJ_09.perc.intra.txt)

**Comment by MatthewThe** [comment]
This should be resolved by b8fde7bd0ca16c13b682a6188309c9b36efb951a. We will release a new version within the next few days, which should include this fix.

When I tested with the most recent build, percolator ran without issues, but you unfortunately still get 0 significant hits at q<0.01 for the inter set after training. You can either set a higher q-value threshold with the `--testFDR` flag or set the `--override` flag, which will at least score your hits as good as possible.

**Comment by MinHuang0129** [comment]
Thanks Matthew, I'll try to fix it using your method.
Will let you know whether it works.
