### ISSUE TITLE
msgf2pin decoy labels

### ISSUE THREAD

**Issue by TnakaNY** [percolator/percolator#217]
Hi,
I am beginner on percolator program. 

I have a problem in analyzing MSGFplus(latest ver) data with percolator. 
When I converted a data file from .mzid to pin.tab file format by msgf2pin latest version, msgf2pin labels all PSMs as +1 including decoy PSMs. So, percolator could not proceed its analysis. 

Does anyone have same problem?

Used command in MSGF analysis;
$ java -jar MSGFPlus.jar -s test.mzXML -o test.mzid -d Uniprot_human_20170801.fasta -t 10ppm -m 0 -inst 1 -e 1 -ti -1,2 -ntt 1 -tda 1 -minLength 6 -maxLength 50 -n 1 -thread 14 -mod modification.txt -addFeatures 1

Used command in msgf2pin;
$ msgf2pin test.mzid -o test_pin.tab

Used command in percolator;
$ percolator test_pin.tab -X test_percolator.xml

Very best

**Comment by MatthewThe** [comment]
MSGFplus adds `XXX_` as a decoy prefix instead of `random_` which is what percolator expects. This is easily solvable by adding the `-P` flag to msgf2pin:

$ msgf2pin test.mzid -o test_pin.tab -P XXX_

**Comment by TnakaNY** [comment]
Hi,
Thank you for quick reply.
I will try it.

Thank you very much!
