### ISSUE TITLE
msgf2pin can not find the mzIdentML1.1.0.xsd file

### ISSUE THREAD

**Issue by Zhanglesolanin** [percolator/percolator#223]
Hi,
I am using the msgf2pin to perform the pin format convert. 
But it throw 
`XML parser warning at :0:0
  warning: unable to open primary document entity '/usr/share/percolator/xml-1-1/mzIdentML1.1.0.xsd'
/usr/share/percolator/xml-1-1/mzIdentML1.1.0.xsd: error: unable to load`

I find this mzIdentML1.1.0.xsd file in another path. 

However, I don't have superuser privileges, and the system manager refuse to help me. So I can not solve this problem directly by moving the file location. I tried to change my environment variables, it didn't work. I also tried to reinstall the percolator by setting `CPACK_RPM_PACKAGE_RELOCATABLE` to `TRUE` and `CPACK_SET_DESTDIR` to `FALSE` in CPack.txt. It didn't work, too.

What should I do to let the msgf2pin find it?

If I need to reinstall the package, please tell me that which parameters should I reset.

Best wishes,

ZhangLe

**Comment by MatthewThe** [comment]
One thing you could try is manually setting the directory where the binaries look for xml files:
https://github.com/percolator/percolator/blob/b41fef2efe46e1943a772d09fb394e13becc50db/CommonCMake.txt#L86

For example, by setting `set(WRITABLE_DIR /home/thisuser/${XML_REL_PATH})` you can put your xsd file at `/home/thisuser/share/percolator/xml-1-1/mzIdentML1.1.0.xsd`. Note that you would still have to copy the xsd files to this directory manually.

**Comment by Zhanglesolanin** [comment]
![image](https://user-images.githubusercontent.com/32329654/44193311-fbe9b880-a164-11e8-8299-79ae1e560a3d.png)

Thank you for help me. I did what you said. Then I got this. 
I am checking for possible errors.
I want to know if I can't install it. Can I write a ms-gf2pin program myself to do the same thing? It seems that what this program does is just a format conversion?

Best wishes,
ZhangLe

**Comment by MatthewThe** [comment]
Could you perhaps share the `CMakeOutput.log` file mentioned in your screenshot?

Unfortunately it's not _just_ a format conversion, as `msgf2pin` calculates some features that are not already present in the mzid file. It is in theory of course possible to recreate those features, but I wouldn't recommend it.

**Comment by Zhanglesolanin** [comment]
[CMakeOutput.log](https://github.com/percolator/percolator/files/2292881/CMakeOutput.log)
I placed the information in the attachment.
Thanks.

**Comment by MatthewThe** [comment]
Thanks for the file, unfortunately it did not contain any useful hints. 

One thing that is a bit odd is that you are using Boostdb instead of TokyoCabinet for serialization (`-DSERIALIZE="TokyoCabinet"`) Are you using one of the build scripts in the `admin/builders` folder?

**Comment by Zhanglesolanin** [comment]
Very sorry for the late reply. 

I tried to use the admin/builders/centos64_build.sh script before. But I don't have the root  privileges. It failed.

The problems we discussed above were all be found when I installed them from source code using cmake.

![image](https://user-images.githubusercontent.com/32329654/44446846-eb2fbb80-a618-11e8-974c-faa253e7e77c.png)

**Comment by MatthewThe** [comment]
Alright, I understand now. Can you try starting from the beginning (i.e. remove the percolator directory completely and pull again from github) and use this command instead of just running `cmake`:
```
cmake -DCMAKE_INSTALL_PREFIX=<insert your preferred install directory here>
```
you won't need the `set(WRITABLE_DIR ...)` change in this case.

**Comment by Zhanglesolanin** [comment]
You are really the most enthusiastic and responsible software author I have ever seen.

But unfortunately, my colleagues and I tried it many times as you said, and still can't install successfully. We have recently used the win version of msgf2pin as a replacement. However, this means that we cannot automate the process under Linux.

In order to integrate msgf2pin into the automated analysis pipeline of our research group, I tried to write a msgf2pin format conversion program using perl. I have figured out how the values in the output file are converted, except for enzint.

Is it convenient for you to tell me how to calculate the value of enzInt? I found this value to be proportional to the number of K/R amino acids in the identified peptide. But I am using the parameter setting of -e 0, why this value is related to the enzyme cleavage site of trypsin. This makes me feel confused.

Thank you.

**Comment by Zhanglesolanin** [comment]
Sorry, I did not describe it clearly. `-e 0` is the parameter when I am running MS-GF+.
Thank you for your help, I have figured out the calculation method of enzInt. In addition, I would like to ask the value of dM, I calculated the dm value according to the 352th line of your script, but the calculation result is not the same as the output value of the original msgf2pin.

`percolator/src/converters/MsgfplusReader.cpp`
`double dM = (observed_mass - (IsotopeError * neutron / charge) - theoretic_mass) / observed_mass;`

For example, one of my results is as follows
experimentalMassToCharge=582.9937744140625
calculatedMassToCharge=582.99365234375
IsotopeError=0
chargeState =3

dm=(582.9937744140625 - (0 * 1.0033548378 / 3) - 582.99365234375) /582.9937744140625
= 2.094*10^-7

But the value I got with the win version of msgf2pin is -0.000000386944.

Can you tell me where this is going wrong?

**Comment by MatthewThe** [comment]
That's very strange, I don't know what could have caused that. Could you send me a (small) example (input mzid + output pin file)?

**Comment by Zhanglesolanin** [comment]
[example.zip](https://github.com/percolator/percolator/files/2350980/example.zip)


This is a small compressed file containing a target mzid, a decoy mzid and an output pin file. 

The example I mentioned above is the first record of the decoy file.

**Comment by MatthewThe** [comment]
Thanks for the files!

Your version of the dM calculation is the correct one. I found a bug in percolator, where the XML parser rounded down the calculatedMassToCharge to 3 digits, e.g. 582.994. I will fix this.
