### ISSUE TITLE
msgf2pin outputs m/z value in "Mass", CalcMass and ExpMass columns

### ISSUE THREAD

**Issue by ghost** [percolator/percolator#227]
Hi percolator team, 
I am using the msgf2pin to convert mzid (from MS-GF+ v2017.01.13) file into pin file, so I can run the percolator (or crux percolator). 
However, I noticed that the value in "ExpMass", "CalcMass", and "Mass" columns in resulting pin file are not correct. Base on the table 1 (figure below) in your [JPR 2014 paper](https://www.ncbi.nlm.nih.gov/pubmed/24344789), I would assume the peptide mass is actually calculated and write into the "Mass" column in pin, but the value in that column is actually m/z value (please the examples below)

- Part of Table1 below
![image](https://user-images.githubusercontent.com/17267760/45247014-78317080-b2b9-11e8-9314-3f3c339e245c.png)

Columns in pin file
- ExpMass and CalcMass columns
![image](https://user-images.githubusercontent.com/17267760/45247039-a616b500-b2b9-11e8-9218-12c8107545ad.png)

- Mass column
![image](https://user-images.githubusercontent.com/17267760/45247056-b7f85800-b2b9-11e8-99f8-97f5d8673698.png)

- Peptide column
![image](https://user-images.githubusercontent.com/17267760/45247069-ce061880-b2b9-11e8-8da2-54f2976e7628.png)

Since downstream tools (such as percolator and crux percolator) assume the CalcMass, ExpMass and Mass are "Mass" value of peptides (not m/z), the downstream reports (for example .pout) then reports incorrect <exp_mass> and <calc_mass> due to the "CalcMass", "ExpMass" and/or "Mass" in pin file from msgf2pin. 

I am wondering if you are willing to change the value in those columns into actual Mass value, not m/z. 
Thanks!
Best,

**Comment by MatthewThe** [comment]
Hi, sorry for the slow reply. Changing it could break some other downstream applications that expect m/z instead of mass. I'll do a quick check of the main downstream packages for percolator to see if we can safely change this.

**Comment by maohi** [comment]
Hello, Thank you so much for your time :) looking forward to hearing from you
