### ISSUE TITLE
The way of detection separate search or concatenated search may be wrong

### ISSUE THREAD

**Issue by fcyu** [percolator/percolator#228]
Hi,

I am using Percolator with a pin file from combining multiple fractions' PSMs. I have made sure that there was only one entry for one "id". However, there may be multiple identical "scannr" since they are from different fractions. Thus, the pin file looks like the following:

id | label | scannr | score | ...
-- | -- | -- | -- | --
F1-02YFC2 | 1 | 2 | 11.34 | ...
F1-03YFC2 | 1 | 2 | 12.94 | ...
F1-04YFC2 | -1 | 2 | 11.42 | ...
F1-05YFC2 | 1 | 2 | 4.82 | ...
F1-06YFC2 | -1 | 2 | 6.84 | ...
F1-07YFC2 | 1 | 2 | 4.96 | ...

In running Percolator with the command
```
percolator.exe" --only-psms --no-terminate --protein-decoy-pattern ###REV### --picked-protein TAIR10_target_REV.fasta --protein-report-fragments --protein-report-duplicates --results-proteins protein2.tsv --results-psms psm2.tsv input.pin
```

The first several lines reads:
```
Percolator version 3.02.nightly-4-2a55db2, Build Date Sep  7 2018 11:22:07
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas K盲ll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
Issued command:
C:\Program Files\percolator-v3-02\bin\percolator.exe --only-psms --no-terminate --protein-decoy-pattern ###REV### --picked-protein TAIR10_target_REV.fasta --protein-report-fragments --protein-report-duplicates --results-proteins protein2.tsv --results-psms psm2.tsv input.pin
Started Mon Sep 10 13:11:49 2018
Hyperparameters: selectionFdr=0.01, Cpos=0, Cneg=0, maxNiter=10
Reading tab-delimited input from datafile input.pin
Features:
score delta_c delta_L_c abs_ppm logEValue ionFrac totalIonIntensity charge1 charge2 charge3 charge4 charge5 charge6
Found 2652121 PSMs
Separate target and decoy search inputs detected, using mix-max method.
Train/test set contains 2234747 positives and 417374 negatives, size ratio=5.3543 and pi0=1
Warning: The mix-max procedure is not well behaved when # targets (2234747) != # decoys (417374). Consider using target-decoy competition (-Y flag).
Selecting Cpos by cross-validation.
Selecting Cneg by cross-validation.
...
```

There is a sentence says that "Separate target and decoy search inputs detected, using mix-max method.", which indicates that Percolator detected it incorrectly. After checking the code, I found that in the SetHandler.cpp file
```C++
      ScanId scanId = getScanId(psmLine, label, optionalFields, lineNr);
      bool isDecoy = (label == -1);
      if (scanIdLookUp.find(scanId) != scanIdLookUp.end()) {
        if (concatenatedSearch && isDecoy != scanIdLookUp[scanId]) {
          concatenatedSearch = false;
        }
      } else {
        scanIdLookUp[scanId] = isDecoy;
      }
``` 
Unfortunately, the "scanId" is a "std::pair<int, double>" where the first int is the "scannr" that may be "duplicated" in different fractions.

I guess using the "id" as the identifier may address this issue. Since it may relate to many codes, I have to submit an issue rather than a pull request.

Thanks,

Fengchao

**Comment by fcyu** [comment]
Thanks for the prompt reply. I have one more question: Does Percolator identify different PSMs according to their "id", which is in the first column, along the whole process?

**Comment by MatthewThe** [comment]
No, the id column is not actually interpreted anywhere. It's just "copied" to the percolator output files.

**Comment by fcyu** [comment]
If so, how Percolator distinguishes the PSMs with the same "scannr" but from different fractions? Like my example.

Thanks

**Comment by MatthewThe** [comment]
We use the combination of ScanNr and ExpMass to distinguish scans from different fractions. This is not ideal, but it would probably solve your problem.

**Comment by fcyu** [comment]
Could you please tell me where the ExpMass column should be? I checked the [https://github.com/percolator/percolator/wiki/Interface (https://github.com/percolator/percolator/wiki/Interface) but I couldn't find one.

Thanks

**Comment by MatthewThe** [comment]
Thanks for pointing that out, that wiki page should be updated. The ExpMass column should come right after the ScanNr column, before any of the feature columns.

**Comment by fcyu** [comment]
Thank you very much. I will try it soon.
