### ISSUE TITLE
Q values for all PSM's

### ISSUE THREAD

**Issue by StevenVerbruggen** [percolator/percolator#229]
Hi,

For our analysis, we are interested in the Q values of all PSM hits. We submit a tab input file of 15 possible hits per spectrum. In the output target psms files where the Q values are shown, only the best-scoring PSM per scan is outputted. We tried by setting the test FDR to 1 in order to not filter on the output, but still only the best-scoring PSM is sent to the output file. We searched in the command line arguments for a parameter to adapt this in the output, but did not found that so far.

Is there a way to get the Q values of all PSMs?

**Comment by percolator** [comment]
Yes, you can do so using the -U flag when invoking percolator. Thanks
--Lukas

**Comment by StevenVerbruggen** [comment]
I executed the pipeline with testFDR 1 and the -U flag:
```
percolator/usr/local/bin/percolator --weights prosit_noenr_combined_weights.csv --post-processing-tdc -U --testFDR 1 --results-psms prosit_noenr_combined_target.psms --decoy-results-psms prosit_noenr_combined_decoy.psms ../prosit_noenr_combined.tab
```

However, still only the best-scoring PSM's are sent to the results .psms files

This is a part of the output log:
```
Found 1827866 test set PSMs with q<1.
Selected best-scoring PSM per scan+expMass (target-decoy competition): 228149 target PSMs and 39347 decoy PSMs.
Calculating q values.
Final list yields 228149 target PSMs with q<1.
```
There are around 3 400 000 PSMs in the input tab file. What could be the reason the `-U` option apparently does not work?

**Comment by MatthewThe** [comment]
It's actually the `-y` flag (--post-processing-mix-max) that controls this.

**Comment by percolator** [comment]
Oups! You are right, Matthew.

**Comment by StevenVerbruggen** [comment]
Thanks! The `-y` flag did the trick!
