### ISSUE TITLE
element 'MzIdentML' declares duplicate identity constraint unique values

### ISSUE THREAD

**Issue by cdlawless** [percolator/percolator#230]
Hi,
I'm having a issue with the msgf2pin converter that I've not come across before, involving duplicate values.

The error is:
XML parser error at C57_F_1_target.mzid:2026098:166
error: element 'MzIdentML' declares duplicate identity constraint unique values

The command run is:
msgf2pin C57_F_1_target.mzid C57_F_1_decoy.mzid

which are the results files for target/decoy searches against a forward/reversed mouse proteome using MSGF+ (v2018.09.12).

The search results files are here:
https://www.dropbox.com/s/a6751sdwkxmrill/C57_F_1_target.mzid?dl=0
https://www.dropbox.com/s/4yywijp97xkmmtb/C57_F_1_decoy.mzid?dl=0

Any help appreciated.

Craig

**Comment by MatthewThe** [comment]
This seems to be a bug in MSGF+ caused by a duplicate PeptideEvidence id (`PepEv_7658488_LSTM+16SPR_32`), which violates the XSD schema. The quick fix is to simply remove this line (line number 2026098), though it might be better to file a bug report with the MSGF+ developers.
