### ISSUE TITLE
Percolator protein inference: non-enzymatic cleavage warnings

### ISSUE THREAD

**Issue by StevenVerbruggen** [percolator/percolator#231]
Dear all,

I started doing protein inference with MaxQuant, but as we could expand the features with several new ones, I want to use Percolator to do the protein inference and combine all features together (both MaxQuant Andromeda scores and new features).

I used the following command:

```
percolator mapped_output.tab --results-psms beforeKR/target_psms.tsv --decoy-results-psms beforeKR/decoy_psms.tsv --results-proteins beforeKR/target_proteins.tsv --decoy-results-proteins beforeKR/decoy_protein    s.tsv --weights beforeKR/weights.csv --picked-protein decoy_beforeKR_cont_incl.fasta --protein-decoy-pattern REV__ --protein-enzyme trypsinp --protein-report-fragments --protein-report-duplicates --only-psms -y
```

The input tab file is a tab separated listing of all PSMs with their included PSM id, all features (MaxQuant + new features) and the link to the proteins per PSM.

The FASTA file we used is the original FASTA file we used with MaxQuant but with contaminants and decoys added. The contaminants consist of the set of MaxQuant contaminants (with CON__ pasted in the accession line) and the decoys are generated based on the original sequences of the FASTA but with the peptides in between 'K' or 'R' reversed (as TrypsinP was used as cleavage enzyme in our data).

I included the STDOUT report in attachment.
You can see in this report that Percolator reports miscleavages and non-enzymatic flanks, although, if I search for these peptide fragments in the FASTA file, borders seem to be cleaved normally (start/end of protein or K/R).
```
Miscleavage detected: _.RVEELGDLAQAHIQQLSEAAGEDDHFLIR._
Non enzymatic flank detected: _.RVEELGDLAQAHIQQLSEAAGEDDHFLIR._
Miscleavage detected: _.SKDDQVTVIGAGVTLHEALAAAELLKK._
Non enzymatic flank detected: _.NKDQEVNFQEYVTFLGALALIYNEALKG._
Warning: more than half of the cleavage sites are non enzymatic, please verify that the right protease was specified.
Protein digestion parameters for duplicate/fragment detection (detected from PSM input):
 enzyme=trypsinp, digestion=non-specific, min-pept-length=6, max-pept-length=30, max-miscleavages=2
```

Furthermore, the number of identified protein groups is 632. Previously, with MaxQuant we got around 4200 protein groups, so this number seems quite low to me.
```
Eliminated lower-scoring target-decoy protein: 42775 target proteins and 35896 decoy proteins remaining.
Computing protein statistics.
Number of protein groups identified at q-value = 0.01: 632
```

And last, I included the ```--protein-report-fragments``` and ```--protein-report-duplicates``` options but still, in the target proteins results file, only one protein per protein group is present. Is this normal? Shouldn't there be a comma-separated list of all protein per protein group?

Thanks in advance for all help with these questions,

Steven

[nohup_percolator_pi.txt](https://github.com/percolator/percolator/files/2533958/nohup_percolator_pi.txt)

**Comment by MatthewThe** [comment]
I think the main issue is the way the flanks are reported in your input file. In Percolator we use `-` instead of `_` to denote unknown flanking amino acids. As you have noted, this causes Percolator to think that a non-specific cleavage was used.

As for the protein inference, you will likely still see a drop in the number of protein groups compared to MaxQuant, because Percolator groups proteins on their in-silico digest, rather than the observed peptides. We discard shared peptides, because, to the best of our knowledge, there is no method available that incorporates these while retaining well calibrated false discover rates (see our [Percolator 3 paper](https://link.springer.com/article/10.1007/s13361-016-1460-7)).

I hope that answers some of your questions, let me know if things are still unclear.

**Comment by StevenVerbruggen** [comment]
Ok thanks for the quick response. Appreciated!
I will first reformat the flanks in the input file from ```_.``` to ```-.``` and see what that gives in Percolator. I will keep you updated.
