### ISSUE TITLE
Difference PSM iteration vs final output

### ISSUE THREAD

**Issue by willems533** [percolator/percolator#236]
Hey everyone,

I have a question similar to the one posed in https://github.com/percolator/percolator/issues/152 .
I have a percolator input file from the same concatenated target-decoy search. I am using a reduced feature set (derived from a Comet search) and an extended feature set totaling 70 features. Now when I run Percolator (-Y mode) for the reduced and extended features the iterations are as follows:

USING 18 FEATURES (REDUCED SET)
---Training with Cpos selected by cross validation, Cneg selected by cross validation, initial_fdr=0.05, fdr=0.05
Iteration 1: Estimated 105 PSMs with q<0.01
Iteration 2: Estimated 168 PSMs with q<0.01
Iteration 3: Estimated 174 PSMs with q<0.01
Iteration 4: Estimated 177 PSMs with q<0.01
Iteration 5: Estimated 178 PSMs with q<0.01
Iteration 6: Estimated 179 PSMs with q<0.01
Iteration 7: Estimated 179 PSMs with q<0.01
Iteration 8: Estimated 179 PSMs with q<0.01
Iteration 9: Estimated 179 PSMs with q<0.01
Iteration 10: Estimated 179 PSMs with q<0.01

(USING EXTENDED FEATURES)
---Training with Cpos selected by cross validation, Cneg selected by cross validation, initial_fdr=0.05, fdr=0.05
Iteration 1: Estimated 259 PSMs with q<0.01
Iteration 2: Estimated 283 PSMs with q<0.01
Iteration 3: Estimated 300 PSMs with q<0.01
Iteration 4: Estimated 319 PSMs with q<0.01
Iteration 5: Estimated 329 PSMs with q<0.01
Iteration 6: Estimated 334 PSMs with q<0.01
Iteration 7: Estimated 339 PSMs with q<0.01
Iteration 8: Estimated 342 PSMs with q<0.01
Iteration 9: Estimated 345 PSMs with q<0.01
Iteration 10: Estimated 345 PSMs with q<0.01

Now from these iterations I intuitively think the extended feature set is doing a good job, so you'd expect more identifications with Qval < 1 / 5% in the psm and peptide reports. However this is not the case, as the numbers are very similar. Also these numbers are not in range as to the iterations, so there are barely PSMs with a q-value < 1% in the final PSM reports.

Now it is a very challenging data set with not alot of positive identifications, so perhaps this is more related to this? Note that I used a --trainFDR of 0.05, though the same trend is true for the default setting. I also use --override to avoid the resetting of the final vector weights.  Now regarding the issue 152 topic I mentioned above, I have no redundant scan numbers. Perhaps I would have to fine-tune somehow the percolator settings to accommodate more challenging searches with less identifications? A main goal is to see how the extensive feature set can aid in distinguishing correct PSMs compared to the reduced feature set. 

Thanks in advance for your feedback,
Patrick

**Comment by MatthewThe** [comment]
Hi Patrick,

Sorry for the slow reply. With such low numbers of positive identifications, it is quite common that we obtain some overfitting during the cross validation, which results in the vastly different numbers between the numbers reported during the iterations and the final number. We have previously looked at addressing this with the experimental flag `--nested-xval-bins`, though in our tests this did not help as much as we had hoped.
