### ISSUE TITLE
Fido Protein Inference Within Percolator

### ISSUE THREAD

**Issue by rmmiller22** [percolator/percolator#239]
Hi,
I was just curious if when utilizing Fido protein inference on a pin.tab file with the -A command, does percolator automatically recalculate q-values prior to protein inference, or do these commands need to be ran separately. Thank you!

**Comment by MatthewThe** [comment]
I am guessing you managed to figure this one out yourself, but for other people that might have the same question: percolator does recalculate q-values on PSM and peptide-level prior to protein inference, without 
the need to specify any extra flags.
