### ISSUE TITLE
Why is the opposite number of score used as the input for qvality to calculate q-value and PEP in picked protein?

### ISSUE THREAD

**Issue by lhuangjs** [percolator/percolator#241]
Why is the **opposite number** of score used as the input for qvality to calculate q-value and PEP in picked protein?

https://github.com/percolator/percolator/blob/a8f00069b7724e4fa1a756f839c9774110ff85cc/src/PickedProteinInterface.cpp#L369

My guess: because the smaller score for `FISHER` and `PEPPROD`  is better, you wanted to use the same `qvality` command(`qvality target decoy -r ...`). And then you chose the opposite of score as `qvality` input. It is right?

**Comment by MatthewThe** [comment]
Yes, your guess is correct.
