### ISSUE TITLE
Exception caught: invalid string position

### ISSUE THREAD

**Issue by ShuaijianDAI** [percolator/percolator#242]
Hi,

I just got the error when I was using the percolator-v-3.02 for my mascot results.
It was ok to produce the peptide results but when it came to the protein, there was something wrong. Below is the log of the percolator. 

Protein digestion parameters for duplicate/fragment detection (detected from PSM input):
 enzyme=trypsin, digestion=full, min-pept-length=9, max-pept-length=117, max-miscleavages=3
Detecting protein fragments/duplicates in target database
Detecting protein fragments/duplicates in decoy database
Initialized protein inference engine.
Computing protein probabilities.
Performing picked protein strategy
Exception caught: invalid string position

**Comment by MatthewThe** [comment]
Seems like something is going wrong with parsing the protein names. Would it be possible for you to share the full log and the input files?

**Comment by ShuaijianDAI** [comment]
[log.txt.txt](https://github.com/percolator/percolator/files/3385778/log.txt.txt)
This is the full log. For the input files, they are too large to be uploaded. You may click the link to download.
https://hkustconnect-my.sharepoint.com/:u:/g/personal/sdaiad_connect_ust_hk/EYgno5wSUbBDglZwoDNsXnsBu5I1Ip_cJdTWOaOA0kMkjA?e=pubH7e.
Thanks.

**Comment by MatthewThe** [comment]
Thanks, I don't have good internet access now, so I haven't been able to download your input files. However, judging from the log I can imagine that you haven't set the correct decoy prefix. Right now it says `--protein-decoy-pattern decoyPrefix`, is `decoyPrefix` indeed the prefix for the decoy proteins?

**Comment by ShuaijianDAI** [comment]
Thanks for your reply. I replaced the decoyPrefix with "###RND###", but got the same error.
[log.txt](https://github.com/percolator/percolator/files/3415589/log.txt)

**Comment by MatthewThe** [comment]
I think something went wrong with generating the percolator input file. I can see that many decoy PSMs have a protein identifier without the decoyPrefix, e.g.
```
id             label    ...    peptide                                         protein
C_F1YFC65543   -1      ...     -.nS[79.966]LM[15.995]VKNTGTTDSTAETVLRKc.-      O14628-7
```

From your fasta file, I can see that the peptide from this decoy PSMs indeed stems from a decoy protein `###RND###sp|O14628-7...`, but apparently the wrong (lacking the `###RND###` prefix) protein identifier was attached to this PSM. Did you generate the percolator input file yourself, or was this generated by Mascot?
