### ISSUE TITLE
help needed: how to NOT toss out redundant PSMs

### ISSUE THREAD

**Issue by Bin-Go1** [percolator/percolator#244]
When I used Percolator 2.9 to find the credible cross-linked peptides with the input data generated by Kojak, Percolator showed "tossing out 'redundant' PSMs keeping only the best scoring PSM for each unique peptide." If I actually wanted to see all the redundant PSMs, if there is a way to skip this tossing-out step?  I'm a biochemist and not familiar with programming. I may need some easy-to-following instructions without too complicated technical items. Thanks a lot!

**Comment by timosachsenberg** [comment]
I did not try it but maybe the option:
--only-psms                                  "Do not remove redundant peptides, keep all PSMS and exclude peptide level probabilities." does what you want.

**Comment by Bin-Go1** [comment]
> I did not try it but maybe the option:
> --only-psms "Do not remove redundant peptides, keep all PSMS and exclude peptide level probabilities." does what you want.

Thank you for your help! 
Do you know how to execute Percolator with this option? I only knew using the Command Prompt to run Percolator with a command of "C:\Percolator\percolator-v2-09\bin\percolator.exe." Then, it automatically tossed out redundant PSMs.

**Comment by MatthewThe** [comment]
Timo's suggestion is indeed probably what you're looking for. You should be able to use the `--only-psms` flag. To add this flag you can simply add this flag after the percolator executable, e.g.
```
"C:\Percolator\percolator-v2-09\bin\percolator.exe" --only-psms my_input_file.tsv
```

**Comment by Bin-Go1** [comment]
> Timo's suggestion is indeed probably what you're looking for. You should be able to use the `--only-psms` flag. To add this flag you can simply add this flag after the percolator executable, e.g.
> 
> ```
> "C:\Percolator\percolator-v2-09\bin\percolator.exe" --only-psms my_input_file.tsv
> ```

It works. Thank you so much for your help!
