### ISSUE TITLE
Several fractions

### ISSUE THREAD

**Issue by aalvarezf** [percolator/percolator#245]
Hi, 
Sorry if my question is too naive, i'm quite new in this field... 

I'm working with several TMT10p batches, fractions and different experimental conditions. I'm using MSGF+ and Percolator for identification.
I do not have clear, in which step should I combine fractions... Should it be at the search step and before percolator? Or later, after combine the quantitative and the identification data? 

Thanks

**Comment by percolator** [comment]
There is no standard for this. However, if you merge your lists of PSMs
before percolator, your FDR calculation gets right without further actions.
That is not the case if you merge after percolator, which will force you to
redo the FDR calculation after merge.

Thanks
Lukas

**Comment by aalvarezf** [comment]
Thank you for your quick answer!
Just  to clarify, to avoid redo the FDR calculation, you mean merge together all the fractions per condition and run Percolator per every experiment,  or run everything together in Percolator? 
**The experimental conditions are two, in different TMT10p batches, and 6 fractions per condition ( 12 TMT10p batches at the end)

**Comment by percolator** [comment]
If you have a large enough computer, just merge all 12 runs and then run
percolator. --Lukas
