### ISSUE TITLE
Question on the number of features and types allowed

### ISSUE THREAD

**Issue by trishorts** [percolator/percolator#248]
Successfully run percolator with two features, both doubles.

Tried with 11 features, mixed double and bool. Received the following message:

Exception caught: ERROR: Reading tab file, too many default values present.

First few lines of input here (Replace vertical bar with tab):

SpecId | Label | ScanNr | F1 | F2 | F3 | F4 | F5 | F6 | F7 | F8 | F9 | F10 | F11 | Peptide | Proteins
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
DefaultDirection | - | - | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 | 1 |   |  
0 | 1 | 13645 | 2 | 34.16569 | 1.53424 | 0.203055 | FALSE | 22 | 1 | 1 | 0 | 4 | 4 | R.HVGDLGNVTADKDGVADVSIEDSVISLSGDHC[Common Fixed:Carbamidomethyl on   C]IIGR.T | H7BYH4
1 | 1 | 13682 | 2 | 34.25761 | 0.199854 | 0.338454 | FALSE | 13 | 0 | 0 | 0 | 3 | 4 | K.TAVIDHHNYDISDLGQHTLIVADTENLLK.A | A0A0C4DGS1

**Comment by percolator** [comment]
Can one really use FALSE and TRUE labels as feature input? What happends if
you replace TRUE=1 and FALSE=0? --Lukas

**Comment by trishorts** [comment]
I am going to try that. Thanks

**Comment by trishorts** [comment]
Yes. That worked great. Thanks

**Comment by trishorts** [comment]
I hope you don't mind answering more questions. I see you use a separate column for each possible charge state, with a 1 indicating true in whichever column matched the observed charge state and zeros everywhere else. In the yeast example (excerpt below), you have three allowed charge states. How feasible/advisable is it to go to many more? Could one do top-down data with many charge states (~15)? Any drawbacks?
![image](https://user-images.githubusercontent.com/16841846/64981045-d7d53b00-d880-11e9-9cae-c1249d601b6c.png)

**Comment by MatthewThe** [comment]
Percolator should definitely be able to run with 15 charge state columns. 

Some considerations I can think of off the top of my head:
1. the number of "positive" examples you have for each charge state, i.e. peptides with the specific charge state that are from correct PSMs. If this number is too low, percolator will either not put a meaningful weight on the feature or might over-fit during the training. In both cases the error estimates would still be valid, though the latter could reduce your sensitivity.
2. if you have a very large number of PSMs (many millions) the large number of features could slow down training and use a lot of memory.
