### ISSUE TITLE
elude - differences in retention time outputs from linux (Ubuntu) and windows (x64)

### ISSUE THREAD

**Issue by mwgard** [percolator/percolator#249]
The outputs from Elude using Linux Ubuntu (elude-v3.03) and Windows x64 (elude-v3.03) are significantly different. The output from Linux seems in line with expected iRT values (as the model was trained to output iRT values) and has a good linear correlation with measured RT values, whereas the Windows output does not align with any expected value (outputs on the order of >1e8). I've seen nearly identical results using different models (including those supplied with Elude), different versions of elude (v3.03 and v3.04), and using the `-n` argument (with and without).

Is there a reason for the difference in outputs, and if so, a way to readily convert the Windows output to what I'm seeing for the linux output? Thanks.

Example Linux Output

> &#35; File generated by Elude. Predicted retention times are given below. 
> &#35; Jul 23 2019 , 14:10:33
> Peptide	Predicted_RT
> AAFGGSGGRGSSSGGGYSSGSSSYGSGGR	31.4642
> ADLEMQIESLKEELAYLK	103.11
> ADLEMQIESLTEELAYLK	116.278
> ADLEMQIESLTEELAYLKK	104.975
> ADLTGISPSPNLYLSK	69.7456
> AEDGSVIDYELIDQDAR	69.5236

Example Windows x64 Output

> &#35; File generated by Elude. Predicted retention times are given below. 
> &#35; Jul 23 2019 , 07:36:53
> Peptide	Predicted_RT
> AAFGGSGGRGSSSGGGYSSGSSSYGSGGR	2.55902e+08
> ADLEMQIESLKEELAYLK	2.2453e+08
> ADLEMQIESLTEELAYLK	2.38189e+08
> ADLEMQIESLTEELAYLKK	2.20331e+08
> ADLTGISPSPNLYLSK	2.69071e+08
> AEDGSVIDYELIDQDAR	3.10754e+08

- elude: v3.03
- windows: Windows 10 Enterprise (1803.17134.1009)
- linux: Ubuntu 18.04.1 (Bionic)
- model: [https://github.com/brvpuyve/MS2PIP-for-DIA/blob/master/ELUDE/ELUDE_PAN_HUMAN.model](url)
- example command:

`elude -l ELUDE_PAN_HUMAN.model -e tmp_elude_input.txt -o tmp_eludePredictions_win64-v3-03.txt -p -v 5 `
![elude_windows-linux_output](https://user-images.githubusercontent.com/43005024/65907178-7d140700-e389-11e9-8fb2-616bcd4c6872.png)

[tmp_elude_input.txt](https://github.com/percolator/percolator/files/3672757/tmp_elude_input.txt)
[tmp_eludePredictions_linuxUbuntu_v3-03.txt](https://github.com/percolator/percolator/files/3672758/tmp_eludePredictions_linuxUbuntu_v3-03.txt)
[tmp_eludePredictions_win64_v3-03.txt](https://github.com/percolator/percolator/files/3672759/tmp_eludePredictions_win64_v3-03.txt)

**Comment by MatthewThe** [comment]
Thanks for reporting this issue. I haven't seen this behavior before, but I'll take a look at it.

**Comment by MatthewThe** [comment]
I can indeed reproduce this issue. It seems to be a problem with reading in the model. When I save the model on windows the saved model file is different from the loaded one, while on linux these two files are identical.

```
elude -l ELUDE_PAN_HUMAN.model -s ELUDE_PAN_HUMAN.linux_saved.model -e tmp_elude_input.txt -o tmp_eludePredictions_linux64-v3-03.txt -p -v 5
```

**Comment by percolator** [comment]
Coud this be a problem with the different line endings in windows and linux
("\r\n" vs. "\n")?

**Comment by MatthewThe** [comment]
Apparently the culprit is fseek, which has [unpredictable behavior on windows](https://stackoverflow.com/questions/47256223/why-does-fseek-0-seek-cur-fail-on-windows):

https://github.com/percolator/percolator/blob/a5ee8a59bd32fce69aee04ed8de682ba1d68e591/src/elude_tool/LibsvmWrapper.cpp#L312

The advise is to open the file in binary mode instead of in text mode as is done currently. This might cause problems elsewhere though, since end of line characters are not translated then.

**Comment by MatthewThe** [comment]
I tested opening the file in binary mode and there seem to be no problems so far (reading model files written on windows/linux works on linux/windows respectively). You can try it out with this binary: [elude-v3-04.zip](https://github.com/percolator/percolator/files/3707764/elude-v3-04.zip)
