### ISSUE TITLE
msgf2pin in 3.4 does not run correctly in conda package

### ISSUE THREAD

**Issue by glormph** [percolator/percolator#251]
Hi! On 3.1, I succesfully pass a metafile to msgf2pin (and it outputs `Found a meta file: metafile`). But when I use 3.4 (from bioconda), this approach doesnt seem to work anymore:
```
# msgf2pin -e trypsin -o test3.4.pin -P "decoy_" metafile

Pin-converter version 3.04.0, Build Date Dec 10 2019 13:41:34
Copyright (c) 2013 Lukas Käll. All rights reserved.
Written by Lukas Käll (lukas.kall@scilifelab.se) in the
School of Biotechnology at KTH - Royal Institute of Technology, Stockholm.
Issued command:
msgf2pin -e trypsin -o test3.4.pin -P decoy_ metafile
on 62a135aee412
XML parser error at :0:0
```

**Comment by MatthewThe** [comment]
Hi! I cannot reproduce this error, but it might be something with the XML file rather than the metafile. Can you run msgf2pin on the files listed in your metafile?

**Comment by glormph** [comment]
You're right, if I run it straight up on the mzid file I get the same error.

Attached is the mzid, (which works fine in 3.1)
[perco3.4_error.mzid.txt](https://github.com/percolator/percolator/files/4064160/perco3.4_error.mzid.txt)

**Comment by MatthewThe** [comment]
That makes sense. However, when I run your file locally (Ubuntu 18.04, percolator 3.4) it runs without any issues. Which platform are you using? Does it work with the standalone version of percolator-converters?

**Comment by glormph** [comment]
I'm using bioconda, but, I just realized that there is another xerces library version in the 3.4 environment (to make percolator and openMS work together).
3.4 is on xerces-c 3.2.2
3.1 is on xerces-c 3.1.2

I'll play around with that a bit to see if there is a difference.

**Comment by glormph** [comment]
Cant figure it out really, maybe it has something to do with newer conda versions currently. The parser error is from xerces-c, but not very informative ( https://github.com/apache/xerces-c/blob/63f93ef81ab5844cf303823f8b4aa97f9d672fa0/src/xercesc/util/FileManagers/PosixFileMgr.cpp#L160 ).

Converters seem to build fine but at runtime they crash (sqt2pin is fine, but the XML ones for tandem/msgf are not). This is all under bioconda so I dont expect you to be fixing this, but if there's anything useful you think of, I'd of course like to know :), so feel free to close this issue. I'm guessing there is something weird with the build/link/run environment that stops xerces from reading the files.

**Comment by MatthewThe** [comment]
Alright, yes that looks pretty specific to bioconda/xerces-c. Can't think of anything useful to add at the moment, but if something comes up I'll let you know.

**Comment by glormph** [comment]
Hi Matthew, I have done some digging, I can perfectly build percolator by hand using conda libraries (let's call this case 1), as in https://github.com/bioconda/bioconda-recipes/pull/20099. But I cannot have conda build percolator (case 2). Not sure why, but I'm hoping you'd know something about the following: when I run `strace msgf2pin -v 5 -o test.pin target.mzid decoy.mzid` I get for the working version (1):

```
openat(AT_FDCWD, "/mnt/userdata/jorrit/repos/bioconda-recipes/builddir/percolator-rel-3-04/src/converters/data/converters/msgf2pin/target.mzid", O_RDONLY) = 4
read(4, "<?xml version=\"1.0\" encoding=\"UT"..., 8191) = 8191
write(2, "MzIdentML - MSGF+ format", 24MzIdentML - MSGF+ format) = 24
write(2, "\n", 1
)                       = 1
close(4)                                = 0
openat(AT_FDCWD, "/mnt/userdata/jorrit/repos/bioconda-recipes/builddir/percolator-rel-3-04/src/converters/data/converters/msgf2pin/target.mzid", O_RDONLY) = 4
brk(0xfd3000)                           = 0xfd3000
openat(AT_FDCWD, "/usr/share/percolator/xml-1-1/mzIdentML1.1.0.xsd", O_RDONLY) = 5
mmap(NULL, 167936, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f85954d2000
fstat(5, {st_mode=S_IFREG|0444, st_size=91191, ...}) = 0
read(5, "\357\273\277<!-- edited with XMLSpy v2011"..., 49152) = 49152
...
```

But for the failing case 2:
```
openat(AT_FDCWD, "/tmp/tes.pin", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
brk(0x55b52fd02000)                     = 0x55b52fd02000
brk(0x55b52fd23000)                     = 0x55b52fd23000
brk(0x55b52fd44000)                     = 0x55b52fd44000
openat(AT_FDCWD, "/mnt/userdata/jorrit/testruns/deqms_nfc/work/2e/a9f4c5d6fb27edb15c7d8d6014279c/XC-CLL_20190715_TMT10_setA_325ug_IPG3-10_fr10.mzid", O_RDONLY) = 4
openat(AT_FDCWD, "/mnt/userdata/jorrit/testruns/deqms_nfc/work/2e/a9f4c5d6fb27edb15c7d8d6014279c/XC-CLL_20190715_TMT10_setA_325ug_IPG3-10_fr10.mzid", O_RDONLY) = 5
openat(AT_FDCWD, "/mnt/userdata/jorrit/testruns/deqms_nfc/work/2e/a9f4c5d6fb27edb15c7d8d6014279c/XC-CLL_20190715_TMT10_setA_325ug_IPG3-10_fr10.mzid", O_RDONLY) = 6
read(6, "<?xml version=\"1.0\" encoding=\"UT"..., 8191) = 8191
close(6)                                = 0
openat(AT_FDCWD, "/mnt/userdata/jorrit/testruns/deqms_nfc/work/2e/a9f4c5d6fb27edb15c7d8d6014279c/XC-CLL_20190715_TMT10_setA_325ug_IPG3-10_fr10.mzid", O_RDONLY) = 6
read(6, "<?xml version=\"1.0\" encoding=\"UT"..., 8191) = 8191
close(6)                                = 0
close(5)                                = 0
close(4)                                = 0
openat(AT_FDCWD, "/mnt/userdata/jorrit/testruns/deqms_nfc/work/2e/a9f4c5d6fb27edb15c7d8d6014279c/XC-CLL_20190715_TMT10_setA_325ug_IPG3-10_fr10.mzid", O_RDONLY) = 4
read(4, "<?xml version=\"1.0\" encoding=\"UT"..., 8191) = 8191
write(2, "MzIdentML - MSGF+ format", 24MzIdentML - MSGF+ format) = 24
write(2, "\n", 1
)                       = 1
close(4)                                = 0
openat(AT_FDCWD, "/mnt/userdata/jorrit/testruns/deqms_nfc/work/2e/a9f4c5d6fb27edb15c7d8d6014279c/XC-CLL_20190715_TMT10_setA_325ug_IPG3-10_fr10.mzid", O_RDONLY) = 4
openat(AT_FDCWD, "/mnt/userdata/jorrit/miniconda3/envs/testp/share/percolator/", O_RDONLY) = 5
mmap(NULL, 167936, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f8489bd4000
fstat(5, {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
read(5, 0x7f8489bf0060, 49152)          = -1 EISDIR (Is a directory)
...
```

So, the problem seems to lie in reading the xsd file (which exists). I'm not sure how to do this correctly, its there some kind of variable to specify on build time that makes the lib looks in the correct place?

**Comment by MatthewThe** [comment]
I vaguely remember a similar problem with people trying to install percolator to a non standard location, I'll see if I can dig it up tomorrow. Just to make sure I understand, an xsd file exists at `/mnt/userdata/jorrit/miniconda3/envs/testp/share/percolator/xml-1-1/mzIdentML1.1.0.xsd`?

**Comment by glormph** [comment]
Yes, it does. It's too late in the evening now but I've isolated this to `parser.cxx`, where `s.c_str()` is called, which somehow removes the filename from the path here.

```
22:47:39 BIOCONDA INFO (ERR) /tmp/miniconda/miniconda/conda-bld/percolator_1583790182306/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
_placehold_placehold_placehold_placehold_pla/share/percolator/ TESTING s.c_str()
22:47:39 BIOCONDA INFO (ERR) /tmp/miniconda/miniconda/conda-bld/percolator_1583790182306/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
_placehold_placehold_placehold_placehold_pla/share/percolator/xml-1-1/mzIdentML1.1.0.xsd TESTING s
22:47:39 BIOCONDA INFO (ERR) /tmp/miniconda/miniconda/conda-bld/percolator_1583790182306/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold
_placehold_placehold_placehold_placehold_pla/share/percolator/xml-1-1/mzIdentML1.1.0.xsd TESTING schemaDef
```
More tomorrow

**Comment by glormph** [comment]
I can replicate the behaviour by putting this in e.g. Reader.cpp:
```
/* This will work */
string basepath = "/path/to/my/files/";
string threepath = basepath + "xml-1-1" + "mzIdentML1.1.0.xsd";
cerr << "threepath string: " << threepath << endl;
cerr << "threepath c_str: " << threepath.c_str() << endl;

/* This will not work */
string conpath = Globals::getInstance()->getXMLDir(true) + "xml-1-1" + "mzIdentML1.1.0.xsd";
cerr << "concatenated path string: " << conpath << endl;
cerr << "concatenated path c_str: " << conpath.c_str() << endl;
```
Then I also get:
```
threepath string: /path/to/my/files/xml-1-1mzIdentML1.1.0.xsd
threepath c_str: /path/to/my/files/xml-1-1mzIdentML1.1.0.xsd
concatenated path string: /tmp/miniconda/miniconda/conda-bld/percolator_1583829931229/_test_env_...[cut].../share/percolator/xml-1-1mzIdentML1.1.0.xsd
concatenated path c_str: /tmp/miniconda/miniconda/conda-bld/percolator_1583829931229/_test_env_...[cut].../share/percolator/
```

**Comment by MatthewThe** [comment]
This can happen if `Globals::getInstance()->getXMLDir(true)` ends with a null character `'\0'`. Could it be that conda adds this character somewhere along the way?

**Comment by glormph** [comment]
Would mean that `WRITABLE_DIR` is null-terminated when included from the `Globals.h` header? (Or possibly by cmake when it creates the header file?) 

I wonder what kind of conda building setting could cause that, and if it is a compiler/cmake setting or some kind of build command string problem.

**Comment by MatthewThe** [comment]
Unfortunately, I can't reproduce the error on my own machine, so I can't say for sure where it happens.   Maybe it's related to this issue: https://github.com/conda/conda-build/issues/1674

**Comment by glormph** [comment]
Thanks, it was apparently EXACTLY that issue! Will fix this with basically the first post of that issue, I'll try adding this to the recipe:
`sed -i '54s/WRITABLE_DIR/std::string(WRITABLE_DIR).c_str()/' $SRC_DIR/src/Globals.cpp`

I hope I learned something about C++ in the process. This was quite the bug chase, feels like I took the scenic route :D. Thanks very much for helping out!
