### ISSUE TITLE
How to run Fido independently?

### ISSUE THREAD

**Issue by lhuangjs** [percolator/percolator#252]
I have a peptide list file. It contains It contains PSM, PSM probabilities and peptide-matched proteins. And then I want to do protein inference by Fido. However, I cannot run Fido in percolator as a standalone application(like qvality). Is there any way to achieve it? Thanks

**Comment by MatthewThe** [comment]
We currently do not build Fido as part of the percolator package. You can try to run cmake from the src/fido directory (for examples, see the build scripts for your platform under admin/builders), but I haven't tested this in years.

Alternatively, you can see if the links in the bottom of this page still work: https://noble.gs.washington.edu/proj/fido/
