### ISSUE TITLE
undefined reference in linking

### ISSUE THREAD

**Issue by kfattila** [percolator/percolator#257]
Hi,

I am trying to build crux-toolkit and linking percolator gives the following linking error below. I am not sure where "ddot_", "dscal_" and others should be defined. Could you please give me some hints how to fix this error.We started seeing this error 2 weeks ago.

Thank you for your advice in advance.

...
[100%] Linking CXX executable crux
/home/alice/crux-toolkit/ext/build/src/percolator-build/src/libperclibrary.a(ssl.cpp.o): In function `cglsFun1(int, int*, double const*, double*, int, double*, double*, double, double)':
ssl.cpp:(.text+0x22c): undefined reference to `dgemv_'
/home/alice/crux-toolkit/ext/build/src/percolator-build/src/libperclibrary.a(ssl.cpp.o): In function `cglsFun2(int, int*, double const*, double*, int, int, double*, double*, double*, double*, double, double)':
ssl.cpp:(.text+0x4ed): undefined reference to `daxpy_'
/home/alice/crux-toolkit/ext/build/src/percolator-build/src/libperclibrary.a(ssl.cpp.o): In function `CGLS(AlgIn const&, double, int, double, vector_int const*, vector_double*, vector_double*, double, double)':
ssl.cpp:(.text+0x909): undefined reference to `daxpy_'
ssl.cpp:(.text+0x974): undefined reference to `daxpy_'
ssl.cpp:(.text+0x9bf): undefined reference to `ddot_'
ssl.cpp:(.text+0xb45): undefined reference to `dscal_'
ssl.cpp:(.text+0xb7a): undefined reference to `daxpy_'
ssl.cpp:(.text+0xb9b): undefined reference to `dscal_'
ssl.cpp:(.text+0xc2e): undefined reference to `ddot_'
ssl.cpp:(.text+0xc5f): undefined reference to `ddot_'
ssl.cpp:(.text+0xcc4): undefined reference to `dscal_'
ssl.cpp:(.text+0xcf6): undefined reference to `daxpy_'
ssl.cpp:(.text+0xd1e): undefined reference to `ddot_'
/home/alice/crux-toolkit/ext/build/src/percolator-build/src/libperclibrary.a(ssl.cpp.o): In function `L2_SVM_MFN(AlgIn const&, options*, vector_double*, vector_double*, double, double)':
ssl.cpp:(.text+0x1047): undefined reference to `ddot_'
ssl.cpp:(.text+0x14c9): undefined reference to `ddot_'
ssl.cpp:(.text+0x199d): undefined reference to `dscal_'
ssl.cpp:(.text+0x19d2): undefined reference to `daxpy_'
ssl.cpp:(.text+0x1a1c): undefined reference to `ddot_'
collect2: error: ld returned 1 exit status
src/CMakeFiles/crux.dir/build.make:101: recipe for target 'src/crux' failed
make[2]: *** [src/crux] Error 1
CMakeFiles/Makefile2:538: recipe for target 'src/CMakeFiles/crux.dir/all' failed
make[1]: *** [src/CMakeFiles/crux.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by CharlesEGrant** [comment]
Percolator added some code from  the BLAS library to Percolator as a separate library. The Crux build had to be updated to include that library and the corresponding include files in it's search paths. This was done in commit [06888da089542]( https://github.com/crux-toolkit/crux-toolkit/commit/06888da089542bd5f49c4265104872486f7e23a0 ).

**Comment by kfattila** [comment]
> Percolator added some code from the BLAS library to Percolator as a separate library. The Crux build had to be updated to include that library and the corresponding include files in it's search paths. This was done in commit [06888da089542](https://github.com/crux-toolkit/crux-toolkit/commit/06888da089542bd5f49c4265104872486f7e23a0).
> 
> You should be able to pick up this fix by doing a pull from the current master branch, and doing a clean build.

Thank you a lot!
