### ISSUE TITLE
Error: current implementation can only handle UNIMOD accessions MS:1001460

### ISSUE THREAD

**Issue by heejongkim** [percolator/percolator#260]
Hi,

As I've been using the percolator in sheltered environments, this is very first time to attempt to use with my hands with command line.
I searched a single raw file with MS-GF+ with 1 fixed mod and 4 variable mods with target/decoy combined and addFeatures enabled.

After huddling through compiling percolator and converters, I got the following msg when i attempted to convert mzid to percolator input tab.

**Comment by MatthewThe** [comment]
Duplicate #261
