### ISSUE TITLE
Protein inference problem: ProteinId = PeptideId

### ISSUE THREAD

**Issue by MiguelCos** [percolator/percolator#263]
Hello,

I am trying to execute protein inference on a .tab file generated after a `Prosit` re-scoring (The current `prosit_target.psms`/`prosit_decoy.psms` generated by `Prosit` are only showing a peptide sequence in the `proteinIds` column). 

I needed to modify my `.tab` file, because the scan number was not adequate as it was generated by Prosit.

I use the next command:

```
percolator prosit_2.tab -f human_reference_w_decoys.fasta -l target_protein_result.tsv -L decoy_protein_result.tsv -P "DECOY_"
```

My fasta file looks like this:
```
>A0A024R1R8 
MSSHEGGKKKALKQPKKQAKEMDEEEKAFKQKQKEEQKKLEVLKAKVVGKGPLATGGIKKSGKK
>DECOY_A0A024R1R8 
MGGEHSSKKKALKQPKKQAKEEEEDMKAFKQKQKEQEKKLLVEKAKVGVKGIGGTALPKKSGKK
>A0A024RBG1 
MMKFKPNQTRTYDREGFKKRAACLCFRSEQEDEVLLVSSSRYPDQWIVPGGGMEPEEEPGGAAVREVYEEAGVKGKLGRL
...
```

After execution, the tabular result shows the IDed peptide sequence for both the `ProteinId` and `peptideIds` columns, so it seems like no protein inference was made.

![image](https://user-images.githubusercontent.com/33185213/92509906-49816400-f20b-11ea-9e38-eff093e678ae.png)

I also get the next warning after execution:
```
Warning: No target-decoy protein pairs found for the picked protein strategy.
  Check if the correct decoy pattern was specified with the -P flag;
  if the target protein is called "protA" and the decoy protein "decoy_protA", use the option "-P decoy_".
```

Do you know what I might be doing wrong that could be causing this? Is this a bug?

Many thanks in advance for taking the time to look at this. I am attaching the file that I used as input.

Best wishes,
Miguel
[protein_inference_problem.zip](https://github.com/percolator/percolator/files/5190093/protein_inference_problem.zip)

**Comment by MatthewThe** [comment]
The problem is that Prosit does not actually give the protein sequences in the protein column in the prosit.tab file, but writes "dummy" information (i.e. the peptide sequence again) to the protein column.

Although Percolator could technically map peptides to proteins based on the in-silico digest, we currently assume that the user provides the correct peptide to protein mapping.

**Comment by MiguelCos** [comment]
Many thanks for your answer Matthew.

Would it be then somehow possible to map peptides to proteins with Percolator in the current version? If not, do you have any recommendations for protein inference starting from the Prosit output?

I believe that Prosit does not give the protein names to each peptide because MaxQuant actually does not assign any protein name to its reversed peptide sequences, therefore Prosit cannot match a reverse peptide to a particular reversed protein. Sadly this makes it difficult for protein inference and protein FDR calculation afterward, assuming we start Prosit rescoring from a MaxQuant `msms.txt` file.

**Comment by MatthewThe** [comment]
Unfortunately, Percolator cannot output a peptide to protein mapping at the moment (although it does calculate it internally...). As it's likely not going to be a widely used feature, we probably will not support it in the future either.

The easiest would be to do the in-silico digest yourself and overwrite the protein column in the prosit.tab. I can share a Python script of mine that does an in-silico digest and writes a simple peptide to protein mapping text file.

**Comment by MiguelCos** [comment]
That would be very helpful!

I have almost zero experience with Python but I would try to execute the code on RStudio and maybe try to port the logic behind it in an R script for my purpose afterward. 

I would be glad if you can share your script with me through my e-mail:
migueljcc5@gmail.com.

Thanks!
