### ISSUE TITLE
Error: no decoy PSMs were provided. 

### ISSUE THREAD

**Issue by grimace9527** [percolator/percolator#274]
Hi & Thanks for your reply:
     An exception appears when I am trying to use the command lines in the example: [https://github.com/percolator/percolator/wiki/Example](url) .

The command line:
`percolator -X pout.xml pin.tab > hilic1.psms`

And the exception showed like this:
```
Concatenated search input detected, skipping both target-decoy competition and mix-max.
Train/test set contains 7857 positives and 0 negatives, size ratio=inf and pi0=1
Exception caught: Error: no decoy PSMs were provided.
```

However when I look back the .mzid file generated from MS-GF+, the search settings was correctly set to target/decoy search, and the .mzid file do contain decoy PeptideEvidence like these:
```
<PeptideEvidence dBSequence_ref="DBSeq16478298" peptide_ref="Pep_CNCVLKDFEN+1KMCESAHGNCKC" start="1303" end="1324" pre="K" post="R" isDecoy="true" id="PepEv_16479600_CNCVLKDFEN+1KMCESAHGNCKC_1303"/>
  <PeptideEvidence dBSequence_ref="DBSeq1151037" peptide_ref="Pep_N+1YLAPAWGAPWVIN+1NPARDDRSTSFQTQ+1LGPSGHDAGR" start="315" end="352" pre="R" post="R" isDecoy="false" id="PepEv_1151351_N+1YLAPAWGAPWVIN+1NPARDDRSTSFQTQ+1LGPSGHDAGR_315"/>
  <PeptideEvidence dBSequence_ref="DBSeq1151037" peptide_ref="Pep_N+1YLAPAWGAPWVINN+1PARDDRSTSFQTQ+1LGPSGHDAGR" start="315" end="352" pre="R" post="R" isDecoy="false" id="PepEv_1151351_N+1YLAPAWGAPWVINN+1PARDDRSTSFQTQ+1LGPSGHDAGR_315"/>
```

What's more, when I use the method MzIDToTsv of MS-GF+, the result .tsv file also contains the PSMs from the decoy proteins whose ID start with 'XXX_'.
So...is there anything wrong? Or what should I do to fix this problem? Thanks again for your reply.

**Comment by grimace9527** [comment]
![image](https://user-images.githubusercontent.com/56531544/97298030-ce910d00-188d-11eb-8563-38b6f4b366d3.png)

**Comment by MatthewThe** [comment]
I assume you used the `msgf2pin` program to convert your mzid file? Can you try adding the flag `--pattern XXX_` to the `msgf2pin` command?

**Comment by grimace9527** [comment]
> I assume you used the `msgf2pin` program to convert your mzid file? Can you try adding the flag `--pattern XXX_` to the `msgf2pin` command?

It works! Thanks a lot and I'm sorry that I have ignored the 'Command line options' on the wiki page... It really helps. Thanks again.

**Comment by MatthewThe** [comment]
No problem, glad I could help!
