### ISSUE TITLE
Very simple question (msgf2pin meta file template?)

### ISSUE THREAD

**Issue by BaylorSci** [percolator/percolator#282]
So I am fairly new to this tool, but think its fantastic. My question relates to the conversion from MSGFplus files (.mzid) to pin or tab delimitated using msgf2pin. I think i'm missing something fairly basic. I can use a meta file (provided as a txt file) to successful read my mzid files in. 
However, my issues is arising from the output. I initially thought it would be similar to MSGFplus where if you do not specify an output file name, then it uses the initial file name and replaces .mzid with .pin (for example). This did not work. 

I then tried providing the output filename in the meta file but that did not work. I have searched the internet for an example of a meta file which would allow me to point to this directory and output to another directory ( or even the same), but haven't been successful. 

Currently, i am running through each file individually (and successfully outputting files with specific names), but i have an upcoming project with 170 samples and i want to try and streamline this as much as possible. Any help with this would be much appreciated!!

**Comment by percolator** [comment]
Yes, it is fairly straightforward to specify where you want your output
files to end up. It is mostly dependent on what type of result file you
want to see. Typically you want a file containing the scores of the unique
peptides.. Such a file can be specified by the command line argument -r,
e.g. "percolator -j my.pin -r /my_favorite_disk/the_peptides.txt". Check
out the different output files of percolator by "percolator -h"
