### ISSUE TITLE
Build converters from source code

### ISSUE THREAD

**Issue by UKQIDA** [percolator/percolator#283]
Hi, 
I have the attached error logs for building converters on Centos. Can anyone shed a light on what is the problem please? I don't have any clues. 

Regards,
Da
[out.log](https://github.com/percolator/percolator/files/5764106/out.log)

**Comment by MatthewThe** [comment]
Looks like a problem with linking the external libraries. Did you use the `admin/builders/centos64_build.sh` script? If not, could you post the command you used to start the build?
