### ISSUE TITLE
 [MS amanda-percolator converter]

### ISSUE THREAD

**Issue by HonglanLi** [percolator/percolator#285]
Dear all,

I want to run percolator after MS Amanda (stand alone) search.

I got *csv /mzid results file from MS Amanda.

Is there a software that convert MS Amanda's *csv or *mzid file to *pin file for running percolator?

**Comment by MatthewThe** [comment]
We don't have a dedicated converter for MS Amanda at the moment, but it shouldn't be too hard to do.
1. You could try the [OpenMS PercolatorAdapter](https://abibuilder.informatik.uni-tuebingen.de/archive/openms/Documentation/nightly/html/TOPP_PercolatorAdapter.html), which should technically be able to handle *mzid input, but it most likely has never been tested with MS Amanda.
2. If you have some experience with Python, we have examples of converting *csv files into *pin files that we can share with you.
