### ISSUE TITLE
running percolator on multiple fractions

### ISSUE THREAD

**Issue by tekitch** [percolator/percolator#286]
Hi, 

I want to run percolator on the results of a high ph fractionation experiment - I have 12 mzml files and associated comet generated pin files but I'm not sure how to combine the results into a single protein list which combines the results of all 12 fractions - how is this achieved with percolator?

Regards, 

Owen.

**Comment by MatthewThe** [comment]
Percolator now allows including the filename as an extra column to distinguish between different raw files.

Instructions on how to run the converters with multiple input files can be found here: https://github.com/percolator/percolator/wiki/Interface#converters
