### ISSUE TITLE
Interaction effects in percolator

### ISSUE THREAD

**Issue by danielgeiszler** [percolator/percolator#290]
Hi devs,

I’m trying to understand the model architecture in percolator so I can test some features, but I’m a bit lost.

How would I encode interaction effects? Say I want to include a diagnostic ion intensity but only in the case where a variable modification is found. Do I need to add two features such that one encodes the presence of the variable mod and the other encodes the intensity of its diagnostic ion? Or would I have to precode the results so that there is only a single new feature containing zeroes where the modification isn’t found and the ion intensity where it is found?

**Comment by percolator** [comment]
Percolator's final score is a linear combination of the features. Hence you
should strive to design feature that make sense to make linear combinations
from. I am not sure which features that make most sense in your case, but I
think it is safe to implement both schemes, and compare their performance
over some datasets, and then select the scheme that brings you best
performance. However, make sure that you have a decoy model where your
features are representatives of incorrect matches, and not just a
representation of decoy PSMs.

**Comment by percolator** [comment]
Yet another point, a recent reimplementation of percolator, mokapot
https://www.biorxiv.org/content/10.1101/2020.12.01.407270v2
allows you to replace the linear classifier with a non-linear one.

**Comment by danielgeiszler** [comment]
Thanks for the help, Lukas. Some other things came up and I haven't had the chance to try out mokapot yet, but I appreciate the clarification and it seems like that's the best path forward. I'm going to close this so it doesn't clutter up your issues.

Cheers.
