### ISSUE TITLE
Warning about adding percolator to path (Windows)

### ISSUE THREAD

**Issue by pbjarterot** [percolator/percolator#300]
![image](https://user-images.githubusercontent.com/46728406/119687160-44228300-be47-11eb-8025-cf3252e51ba1.png)

There is an issue with adding percolator to path whilst installing in windows. The error message is as can be seen in the attached image that the path is too long for the installer to be able to modify path
The problem was solved by manually adding it to path

System: 64bit Windows 10 Home, Version 19041.985

**Comment by percolator** [comment]
Thanks, could you please tell us the content of your environment variable PATH? If I remember correctly there is a path command in windows just giving you a string.

**Comment by pbjarterot** [comment]
Using 
echo $ENV:PATH.split(";") 
in powershell, the string i am returned is:

C:\Users\patri\documents\github\metinpark\metabolite_identifier\src\gui\Scripts
C:\Program Files\Python37\Scripts\
C:\Program Files\Python37\
C:\Users\patri\AppData\Local\Programs\Python\Python37-32\
C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR
C:\Users\patri\AppData\Local\Programs\Python\Python37-32\Scripts\
C:\Program Files\Git\cmd
C:\Program Files\PuTTY\
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
C:\Program Files\nodejs\
C:\Strawberry\perl\bin
C:\Strawberry\perl\site\bin
C:\Strawberry\c\bin
C:\Program Files\Microsoft VS Code\bin
C:\ffmpeg\bin
C:\Program Files\PostgreSQL\12\bin\
C:\Users\patri\Documents\cmake-3.18.0-win64-x64\bin
C.\ffmpeg\bin\ffmpeg.exe
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
C:\Program Files\MATLAB\R2020b\bin
C:\Users\patri\AppData\Local\Programs\Python\Python39\Scripts\
C:\Users\patri\AppData\Local\Programs\Python\Python39\
C:\Users\patri\PyMOL
C:\Users\patri\PyMOL\Library\mingw-w64\bin
C:\Users\patri\PyMOL\Library\usr\bin
C:\Users\patri\PyMOL\Library\bin
C:\Users\patri\PyMOL\Scripts
C:\Users\patri\AppData\Local\Microsoft\WindowsApps
C:\Users\patri\AppData\Local\atom\bin
C:\Users\patri\AppData\Local\GitHubDesktop\bin
C:\Users\patri\AppData\Local\Programs\Microsoft VS Code\bin
C:\Users\patri\AppData\Roaming\npm
C:\Users\patri\AppData\Local\Programs\MiKTeX 2.9\miktex\bin\x64\
C:\texlive\2019\bin\win32
C:\Users\patri\AppData\Roaming\Python\Python37\Scripts
C:\Users\patri\flutter\bin
c:\Users\patri\AppData\Local\atom\bin
C:\Users\patri\AppData\Local\Programs\Microsoft VS Code Insiders\bin
C:\Users\patri\AppData\Local\Microsoft\WindowsApps
C:\Program Files\percolator-converters-v3-05\bin
C:\Program Files\percolator-v3-05\bin

**Comment by percolator** [comment]
The problem is likely not related to Percolator, but instead on your long
PATH. Do you really need all these directories?

**Comment by pbjarterot** [comment]
I definitely don't need all these directories, but what made me suspect that the issue was related to percolator was that there were no issues adding the path manually in environmental variables.

**Comment by RalfG** [comment]
I had the same issue on two different PCs. Adding to the path manually did work. Could very well be a Windows quirk. 

For future reference, to manually add Percolator to the PATH manually on Windows:
1. Open start
2. Start typing "Environment variables" to search and click on "Edit the system environment variables"
3. Click "Environment Variables..."
4. Select Path (Either in the User or the System field, does not really matter).
5. Click "Edit..."
6. Click "New"
7. Paste in the path to your Percolator `bin` directory. For me, this was `C:\Program Files\percolator-v3-05\bin`
8. Repeat for other Percolator installers, such as `percolator-converters`: `C:\Program Files\percolator-converters-v3-05\bin`
9. Click "OK"
10. Click "OK"
11. Click "OK"
