### ISSUE TITLE
Mix-max p-values?

### ISSUE THREAD

**Issue by mrForce** [percolator/percolator#315]
Hi,

This isn't an issue, so much as a question. I'm trying to make sense of the mix-max option avaliable in Percolator. In PosteriorEstimator.cpp, there's a function called getPValues (which is used to estimate p-values, which are then passed to estimatePi0, which uses the method in section 9 of Storey's Direct FDR paper). This function computes some ratio, involving the number of decoy matches, I believe, but I'm having trouble understanding exactly what it's computing based on the code. Is the underlying math explained in any paper? 

Thanks,

Jordan

**Comment by wsnoble** [comment]
Yes, this method is described here:

"Improved False Discovery Rate Estimation Procedure for Shotgun Proteomics"

https://pubs.acs.org/doi/abs/10.1021/acs.jproteome.5b00081

**Comment by mrForce** [comment]
Thanks Bill!
