### ISSUE TITLE
Reusing Percolator Weights

### ISSUE THREAD

**Issue by jamc1996** [percolator/percolator#316]
Hi,

Thanks for all your work on Percolator, I've really enjoyed using it.

I'm just wondering how the 3CV weights are combined in the final percolator scoring? I thought I read that the model that yields the most PSMs is selected but I don't see an indication in the output on which model that is.

And related to this is it possible to run without training, i.e. get scores on new data from a pretrained percolator model?

Thanks!

**Comment by thabangh** [comment]
On Wed, Nov 3, 2021 at 4:14 AM jamc1996 ***@***.***> wrote:

> Hi,
>
> Thanks for all your work on Percolator, I've really enjoyed using it.
>
> I'm just wondering how the 3CV weights are combined in the final
> percolator scoring? I thought I read that the model that yields the most
> PSMs is selected but I don't see an indication in the output on which model
> that is.
>

The scores from the three classifiers are averaged.  Details are given in
this paper:

https://bmcbioinformatics.biomedcentral.com/track/pdf/10.1186/1471-2105-13-S16-S3.pdf




> And related to this is it possible to run without training, i.e. get
> scores on new data from a pretrained percolator model?
>
>
You can do this with the Python reimplementation, mokapot:

https://pubs.acs.org/doi/abs/10.1021/acs.jproteome.0c01010
https://github.com/wfondrie/mokapot

Cheers.
Bill

**Comment by jamc1996** [comment]
Terrific, thanks for the quick response 👍

**Comment by wsnoble** [comment]
I should have said that you can also reuse models by using the static model functionality, as described here:
