### ISSUE TITLE
google analytics

### ISSUE THREAD

**Issue by glormph** [percolator/percolator#317]
Hej,

Browsing the code I found a file googleanalytics.cpp in the repo. I'm left wondering if percolator posts data to GA on every run, and if so, if one can opt out from that. Not really sure about the implications of this (apart from useful statistics), but I usually err on the paranoid side when it comes to advertising, and this was somewhat unexpected.

**Comment by wsnoble** [comment]
I think this code was borrowed from Crux. We use it to make the real-time
usage bar plot on the main page (http://crux.ms).  I didn't know the code
was also transferred to Percolator, nor if it is in active use there.

In Crux, you can turn this off by giving the option --no-analytics.

[image: image.png]

**Comment by percolator** [comment]
Yes, an option to switch off the GA reporting makes sense, but it is
currently not implemented. I will consider this for future updates.

--Lukas

**Comment by MatthewThe** [comment]
Added in e487451900f357275669123321635628c7873683
Flag is `--no-analytics`
