### ISSUE TITLE
Filenames in Percolator output

### ISSUE THREAD

**Issue by wsnoble** [percolator/percolator#322]
A longstanding problem with Percolator is that the output file does not include filenames, just an index.  Do you think it would be feasible to implement in Percolator an option like this one in tide-search:

    --file-column T|F – Include the file column in tab-delimited output. Default = true.

This would just add an additional column to the output.

**Comment by jvolkening** [comment]
+1

We currently have to add them in by parsing the Percolator log file.

**Comment by percolator** [comment]
I added support for a filename column for tab delimited input and output.
If percolator detects a column named "filename" in input, it will carry over its content to output files.

**Comment by wsnoble** [comment]
Thanks, Lukas. We will work on updating the version of Percolator in Crux so that this new functionality is available there.

**Comment by wsnoble** [comment]
Can you document this behavior somewhere on the percolator website?

**Comment by wsnoble** [comment]
I can't get this to work. Here is the output:

```
$ percolator tide-xcorr/make-pin.pin
Protein decoy-preix used is decoy_
All files have been read
Percolator version 3.06.0, Build Date Jul 12 2022 14:14:54
Copyright (c) 2006-9 University of Washington. All rights reserved.
Written by Lukas Käll (lukall@u.washington.edu) in the
Department of Genome Sciences at the University of Washington.
Issued command:
/net/noble/vol1/home/noble/software/percolator-github/build/src/percolator tide\
-xcorr/make-pin.pin
Started Tue Aug 30 21:39:00 2022
 on pyrrolysine.gs.washington.edu
Hyperparameters: selectionFdr=0.01, Cpos=0, Cneg=0, maxNiter=10
Reading tab-delimited input from datafile tide-xcorr/make-pin.pin

WARNING: Tab delimited input does not contain ScanNr column,
         scan numbers will be assigned automatically.

Features:
Label ScanNr ExpMass CalcMass lnrSp deltLCn deltCn XCorr Sp IonFrac PepLen Charge1 Charge2 Charge3 enzN enzC enzInt lnNumDSP dM absdM
Exception caught: ERROR: Reading tab file, error reading PSM on line 2. Could not read label.
```

Can you tell me whether the "filename" column needs to be in a particular place within the file?  Pin file is attached.

[make-pin.txt](https://github.com/percolator/percolator/files/9458469/make-pin.txt)

**Comment by percolator** [comment]
The first two columns are reserved for id and labels. Placing the filename in column 3 seems to work well:
$ ./percolator make-pin.txt 2> /dev/null | grep -q target ; echo $?
1
$ cat make-pin.txt | awk -v OFS='\t' '{tmp=$1;$1=$2;$2=$3;$3=tmp; print}' > again.pin
$ ./percolator again.pin 2> /dev/null | grep -q target ; echo $?
0
$ cat make-pin.txt | awk -v OFS='\t' '{tmp=$1;$1=$2;$2=$3;$3=$4;$4=tmp; print}' > again4.pin
$ ./percolator again4.pin 2> /dev/null | grep -q target ; echo $?
0

I found some other bugs while building, so I am updating the code in the master based on these operations.

**Comment by wsnoble** [comment]
OK, I have verified that this works for me.  I suggest that you should document this behavior [here](https://github.com/percolator/percolator/wiki/Interface#pintsv-tab-delimited-file-format). Then you can close this issue.
