### ISSUE TITLE
missing `OpenMP` dependency for Linux binaries

### ISSUE THREAD

**Issue by guoci** [percolator/percolator#323]
The Linux binaries require `libgomp.so.1`, but it is not included. This is not a problem for most Linux users because the OpenMP library is usually installed. But it shows up in cases where only a minimal number of packages is installed, such as in a container.
https://github.com/Nesvilab/FragPipe/issues/560#issuecomment-1080676109

**Comment by percolator** [comment]
OpenMP is pretty flexible. If you compile percolator on a machine without
the OpenMP package installed it will no longer link to it. The drawback is
ofcourse that the parallelization of percolator will not work after that.

**Comment by guoci** [comment]
@percolator my point was that the Linux installers don't have it as a dependency. But it is a minor issue I think, so closing
