### ISSUE TITLE
Best practice of running percolator on multiple fractions

### ISSUE THREAD

**Issue by zhuchcn** [percolator/percolator#326]
Hi, my problem is similar to #286 but slightly different although I'm also wondering what would be the best way of handling multiple fractions with percolator. We are using OpenMS' PercolatorAdapter, which allows you combine multiple search engine results together. My question is, for percolator, in the pin tsv file, do the two columns `SpecId` and `ScanNr` affect the final results? Because we tried two ways A. merging search engine results of fractions as they are and B. reindex the spectrum ID so they are non-redundant, and we got quite different scores. When looking at the pin TSV file, everything is the same except these two columns. Pasting a figure here:

![image](https://user-images.githubusercontent.com/29579625/165403960-dcaa70fc-8c79-493f-bf8b-9e0f71485d0e.png)

**Comment by zhuchcn** [comment]
This is what we found so far:
1. For the `ScanNr` column, if we do +1 or x2 to each PSM, the results are the same
2. Reindex `ScanNr` so it reflects the order of spectra based on retention time when multiple fractions are mixed, the results are **not** the same.
3. Manually changing the `ScanNr` of one PSM (from 1080 -> 10800), in the final results, every PSM got a slightly different score.

So does it seem like the order of spectra is somehow used by the algorithm?

**Comment by percolator** [comment]
Apart from annotation, the scannr column just serves the purpose of
dividing the PSMs between cross-validation bins. We ensure that all PSMs
from each MS2 spectrum are allocated to the same cross-validation bin.
I.e. you are free to set it to any value you like as long as you use the
same value for all the PSMs of the same spectrum.
You will see different scores from percolator from one run to another due
to the stochasticity of the cross-validation bin assignment procedure.

Yours
--Lukas

**Comment by zhuchcn** [comment]
Got it, so records with the same ScanNr are treated as the same spectrum. That's what we figured, too. Appreciate the explanation!
