### ISSUE TITLE
I want to reproduce the operation of this article datasets how do I do?

### ISSUE THREAD

**Issue by zerohuwan** [percolator/percolator#331]
Hello, I want to reproduce the operation of this article Semi-supervised learning
for peptide identificationfrom shotgun proteomics datasets how do I do? I would appreciate your help.

**Comment by percolator** [comment]
Hmm, which result in which article is it that you want to reproduce?

**Comment by zerohuwan** [comment]
Thank you for your reply. The original address is as follows.
[https://www.nature.com/articles/nmeth1113#author-information](url)
You measured Percolator’s ability to identify correct PSMs using a yeast dataset containing 35,236 spectra. In this case, Percolator correctly identified 12,691 PSMs, corresponding to 8,197 unique peptides and 1,630 proteins.

**Comment by percolator** [comment]
I see. The datasets are available here:
https://noble.gs.washington.edu/proj/percolator/
The software has evolved significantly since its release. Particularly, you
need to run sqt2pin in order to use sqt files.
--Lukas

**Comment by MatthewThe** [comment]
For future reference: here is a guide on how to run percolator with an example dataset: https://github.com/percolator/percolator/wiki/Example
