### ISSUE TITLE
Setting --subset-max-train Impacts PSM Yield on small datasets.

### ISSUE THREAD

**Issue by jamc1996** [percolator/percolator#332]
Hi,

I've noticed that setting the subset-max-train argument on Percolator has a very large impact on PSM yield even when the number of PSMs in the dataset is much smaller than the value set in the argument.

Apologies I have an example file but Github won't allow me to upload it, but this has been reproducible on every dataset I've applied Percolator to.

I don't need to set this value in my pipeline so if it's a bug I can just remove the subset-max-train argument, I'd just like to know what the correct setting is.

Note: I am still using version 3.05 due to the compatibility issue already reported 
https://github.com/percolator/percolator/issues/329
but I could try to update if there are any relevant changes in v 3.06.

(Edit: I have been able to provide an example, see comment. I've also run it for v 3.06 by updating label and proteins to Label and Proteins in the header of the example.csv and observed the same behaviour.)

Thank you for your help!

Best wishes,
John.

**Comment by jamc1996** [comment]
Sorry I realised the problem with the upload was using a .tab file so it's renamed to example.csv 

[example.csv](https://github.com/percolator/percolator/files/9065609/example.csv)

Running this with:

```
percolator -I concatenated --subset-max-train 5000000 example.csv > example_output.psms
```

yields 1313 target peptides with q<0.01. But running

```
percolator -I concatenated example.csv > example_output.psms
```

yields 1141 target peptides with q<0.01.

**Comment by MatthewThe** [comment]
Hi John,

Apologies for the slow reply. Yes, subset training is indeed not beneficial and potentially detrimental if your dataset is smaller than the value you set it to. It is mainly meant as a way to reduce computational time on (very) large datasets.

**Comment by jamc1996** [comment]
Terrific, thanks for the confirmation 👍 

As a minor future feature request, would it be possible to add a warning if you set --subset-max-train to a value less than your number of PSMs? I'd assumed that the flag would be ignored for small datasets and wouldn't have any impact so I think a warning message of possible overfitting would be really helpful here.
