### ISSUE TITLE
Segmentation fault with 3.06

### ISSUE THREAD

**Issue by micgrab** [percolator/percolator#334]
Hi,
here is a test data set that causes a segmentation fault running on Ubuntu 20.04.4 LTS:
[0_decoy.csv](https://github.com/percolator/percolator/files/9103914/0_decoy.csv)
[1_decoy.csv](https://github.com/percolator/percolator/files/9103916/1_decoy.csv)
But this one works:
[5_decoy.csv](https://github.com/percolator/percolator/files/9104003/5_decoy.csv)

## [percolator-v3-06-linux-amd64.deb](https://github.com/percolator/percolator/releases/download/rel-3-06/percolator-v3-06-linux-amd64.deb)
```
$ percolator 0_decoy.csv 
Segmentation fault (core dumped)
```
```
$ percolator 1_decoy.csv 
Segmentation fault (core dumped)
```
But this works
```
$ percolator 5_decoy.csv 
Protein decoy-preix used is random_seq_378
All files have been read
...
```
Actually, Percolator complains about too good separation but that is expected with this data set

## [percolator-v3-05-linux-amd64.deb](https://github.com/percolator/percolator/releases/download/rel-3-05/ubuntu.tar.gz)
```
$ percolator 0_decoy.csv 
...
Exception caught: Error: no decoy PSMs were provided.
```
:heavy_check_mark: Percolator notices that there are no decoys

```
$ percolator 1_decoy.csv 
...
$ percolator 5_decoy.csv 
...
```
:heavy_check_mark: Percolator works

**Comment by percolator** [comment]
I made a bugfix, PR [337](https://github.com/percolator/percolator/pull/337)
Thanks for a nice bug report!
