### ISSUE TITLE
comma separated protein IDs

### ISSUE THREAD

**Issue by kfattila** [percolator/percolator#343]
Hi,

We were wondering if it would be possible to output a comma separated list of protein ids, (while the other field separators could remain tab-delimited). The current format breaks down for example the Python library pandas' parser. :/

Attila

**Comment by wsnoble** [comment]
This already exists as an option in percolator:

```
-K <char>
 --protein-name-separator <char>                                                                                                                                                                                                                                                          The separator used in tab delimited input and output for separating protein names. Default = tab-char.
```

**Comment by kfattila** [comment]
If I use 
`--protein-name-separator , `
then the stand-alone percolator does not print any protein ID. The column header prints the Protein Ids name, but the whole column is empty.
The very same for `-K `

**Comment by MatthewThe** [comment]
Seems like the problem was with the proteinIds not being printed out correctly (#242). 
For me, it works as expected now.
