### ISSUE TITLE
version 3.06: proteinIds are empty

### ISSUE THREAD

**Issue by picciama** [percolator/percolator#353]
In the output file specified by --results-peptides and --decoy-results-peptides, the proteinIds column is empty.

More specifically, every single proteinID is "", as indiciated by a "\t\n" at the end of each line. I tried to check your code where this error may have been introduced -- to no avail.
My input files are correct and contain a "Proteins" column, as well as a "Label" column. 
Indeed, everything works as expected in v3.05, i.e. it must be an issue with v3.06.

Is that maybe connected to https://github.com/percolator/percolator/issues/329

Is there any change that would require me to invoke percolator differently in v3.06 other than changing my "Protein" column to "Proteins"?

**Edit**
Maybe this is also fixed already on master by https://github.com/percolator/percolator/commit/c34cafbb2f0a96b921ab86b4626980cbf25719da

Command: 
```
percolator
  --weights weights.csv
  --num-threads 4
  --subset-max-train 500000
  --post-processing-tdc
  --search-input concatenated
  --testFDR 0.01
  --trainFDR 0.01
  --results-psms  target.psms
  --decoy-results-psms decoy.psms
  --results-peptides target.peptides
  --decoy-results-peptides decoy.peptides
  rescore.tab
```

OS: Debian 11

**Comment by MatthewThe** [comment]
There is a new release now: https://github.com/percolator/percolator/releases/tag/rel-3-06-01
