### ISSUE TITLE
stopped in Percolator process with an exit code: -1073741819

### ISSUE THREAD

**Issue by terencetdtd** [percolator/percolator#355]
Hi Percolator team

I have been trying the DIA_SpecLib_Quant workflow in FragPipe GUI but failed every time in this "Percolator" process, would you mind taking a look at the log file and offer me some guidance regarding how to get this to work?

Many thanks in advance,
T
[DIA-Speclib_Quant_DT_error_log_2023-06-27_10-42-19.txt.zip](https://github.com/percolator/percolator/files/11915247/DIA-Speclib_Quant_DT_error_log_2023-06-27_10-42-19.txt.zip)

**Comment by Li-Yueyang** [comment]
Hi, I got the same error when processing Percolator. Could you kindly help with it?

Thank you!

**Comment by cfull014** [comment]
Hi, I've also been receiving this error in FragPipe. I've attached the most recent log file.

[log_2023-08-07_09-58-35.txt](https://github.com/percolator/percolator/files/12283148/log_2023-08-07_09-58-35.txt)

Thanks.

**Comment by gcrynen** [comment]
Hi,
I just updated to Fragpipe v20, I never got this error before. But when I am running 60 fractions, I am getting this error. I ran similar search with 4 files (different files not fractions), that search was successful with the same set up. 
I attached the log file from fragpipe.
Thank you.
[log_2023-08-08_60fractions_percolatorerror.txt](https://github.com/percolator/percolator/files/12293734/log_2023-08-08_60fractions_percolatorerror.txt)

**Comment by gcrynen** [comment]
I happened to run the same dataset with FragPipe v18 and percolator step was running fine at the time. I noticed the percolator was topping at files that included less than 100 PSMs, I removed the fractions with less than 250 PSMs and the task completed without errors.

**Comment by MatthewThe** [comment]
Apologies for the late response.

It's hard to see the problem from the error logs.
Would someone be able to share a percolator input file of a run that failed, e.g. `CAP_f07_b_DTDNH_P2306_064_edited.pin`

**Comment by gcrynen** [comment]
Hi,
all files including edited.pin, for sample 3, the failed sample, is in this link:
https://www.dropbox.com/scl/fo/v1xvd9c8w5x5nqj3qy0a0/h?rlkey=70ji1n77jzp3kifi453j6uix9&dl=0

**Comment by MatthewThe** [comment]
It appears that the error is a result of a bug in v3.06 which has been fixed in v3.06.01: https://github.com/percolator/percolator/issues/334

Please contact the MSFragger team to ask if they can upgrade the percolator version to v3.06.01.

**Comment by fcyu** [comment]
Hi @MatthewThe ,

Thank you very much for the prompt help. We will upgrade the Percolator in FragPipe. Could you please share the compiled Windows executable file with us?

Thanks,

Fengchao

**Comment by fcyu** [comment]
Great! I have packaged a pre-released version of FragPipe: https://www.dropbox.com/t/UdCnMklPXXssx4HR

Please let me know if there are any problems.

Best,

Fengchao

**Comment by gcrynen** [comment]
Thank you Matthew and Fengchao for the speedy processing,  much appreciated. However I get a different error this time. It is a MSBooster error, so I will post it in fragpipe github.
