### ISSUE TITLE
Glycoproteomics application

### ISSUE THREAD

**Issue by yuz2011** [percolator/percolator#361]
Hello,
I would like to inquire whether Percolator can be adapted for glycopeptide rescoring. What is the reported False Discovery Rate (FDR) level by Percolator? Is it capable of error control specifically for glycosite, glycan, or glycopeptide?
Thank you

**Comment by MatthewThe** [comment]
As far as I'm aware, we do not have specific support for glycopeptides. 

According to the FragPipe documentation, it is not recommended to use Percolator on glycopeptides as-is: https://fragpipe.nesvilab.org/docs/tutorial_glyco.html

**Comment by yuz2011** [comment]
Thank you very much for your reply!
