### ISSUE TITLE
Running percolator on msgf+ output

### ISSUE THREAD

**Issue by JannikSchneider12** [percolator/percolator#367]
Hey everyone,

I have the problem that the output from my msgf+ run seems not to be recognized. I am getting this error:

(peptideidentification) jannik@DELLXPS:~/percolator$ percolator /home/jannik/data/consensus_spectra/falcon_run_1_50_conservative_binned.tsv
10 -1
Couldn't find 'Proteins' column in tab-file

This shows up  in the .mzid file as well. I also tried to rename the column like this:

import pandas as pd

# Read in TSV file 
file_path = '/home/jannik/data/consensus_spectra/falcon_run_1_50_conservative_binned.tsv'
df = pd.read_csv(file_path, sep='\t')

# Rename the "Protein" column to "Proteins"
df.rename(columns={'Protein': 'Proteins'}, inplace=True)

# Display the DataFrame with the updated column name
display(df)

# Save the DataFrame back to the same TSV file, overwriting the old file
df.to_csv(file_path, sep='\t', index=False)

But this also didnt work. That is how the tsv looks like:

![image](https://github.com/percolator/percolator/assets/72038436/e35fc73b-46c2-47a7-9bff-33856bd830c8)

Can someone help me?

**Comment by glormph** [comment]
That looks like an mzid.tsv output from MSGF+. You have to first use percolator's `msgf2pin` to create the percolator input data which can go into percolator. I'm in a bit of something now so I won't be able to write much more help about how to use it at the moment, so I hope you can figure it out :)

**Comment by JannikSchneider12** [comment]
Thanks for your help. I still have problems with the decoy database. So this is my current error:

(peptideidentification) jannik@DELLXPS:~/msgfplus$ java -Xmx3500M -jar MSGFPlus.jar -s /home/jannik/data/consensus_spectra/falcon_run_1_50_conservative.mgf -d /home/jannik/data/BSA.fasta -tda 1
MS-GF+ Release (v2023.01.12) (12 January 2023)
Java 11.0.21 (Ubuntu)
Linux (amd64, version 5.15.133.1-microsoft-standard-WSL2)
Loading database files...
Creating /home/jannik/data/BSA.revCat.fasta.
java.lang.NullPointerException
        at edu.ucsd.msjava.msdbsearch.ReverseDB.reverseDB(ReverseDB.java:91)
        at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:225)
        at edu.ucsd.msjava.ui.MSGFPlus.runMSGFPlus(MSGFPlus.java:113)
        at edu.ucsd.msjava.ui.MSGFPlus.main(MSGFPlus.java:61)

(peptideidentification) jannik@DELLXPS:~/msgfplus$ java -Xmx3500M -jar MSGFPlus.jar -s /home/jannik/data/consensus_spectra/falcon_run_1_50_conservative.mgf -d /home/jannik/data/BSA.fasta -tda 1
MS-GF+ Release (v2023.01.12) (12 January 2023)
Java 11.0.21 (Ubuntu)
Linux (amd64, version 5.15.133.1-microsoft-standard-WSL2)
Loading database files...
Warning: database does not contain all standard amino acids. Probability 0.05 will be used for all amino acids.
Re-creating the .canno file since metaIdSignature LastModified is not within 2 seconds of the file modification time on disk:
 Expected 1704886305764 (2024-01-10 12:31:45) but actually 1704886890064 (2024-01-10 12:41:30)
Error while reading: BSA.revCat.fasta (fraction of decoy proteins: 0.0)
Delete BSA.revCat.fasta and run MS-GF+ again.
Decoy protein names should start with XXX

Although the start is set to default which is XXX
